### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'onUpdated')

### ISSUE THREAD

**Issue by 0x48piraj** [0x48piraj/fadblock#1]
`chrome.tabs` is not available in a content script by design. Content scripts [can access only 4 chrome API](https://developer.chrome.com/extensions/content_scripts) so `chrome.tabs` is only available in a background/popup or other internal extension page that has `chrome-extension://<extension-id>/ URL`.

[Content script](https://developer.chrome.com/docs/extensions/mv3/content_scripts) can only use chrome.`i18n`, chrome.`dom`, chrome.`storage`, and a subset of chrome.`runtime`/chrome.`extension`.

Most chrome APIs such as `chrome.tabs` are only available the background script (service worker in MV3), popup script, etc.

### Solution
[Pass a message](https://developer.chrome.com/extensions/messaging) from the content script to the [background script](https://developer.chrome.com/docs/extensions/mv3/service_workers/) and use the API there.

**Comment by 0x48piraj** [comment]
Thanks to **r/CutTheRedLine** and **r/No_Paleontologist700** for reaching out.

**Comment by git-pixel22** [comment]
Hello @0x48piraj,

I hope you're doing well. I wanted to mention something slightly different but relevant. I think we should include this URL to explain the point highlighted in the screenshot I've attached below.

<br>

![image](https://github.com/0x48piraj/fadblock/assets/84857474/6b995300-066d-494a-bf71-daca6a6d1209)

<br>

URL - https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#webextension_apis

I went through the URL you've attached but was not able to find anything related to that content scripts can access only 4 Chrome APIs.

I found this closed issue when I faced the same error which is mentioned in the issue statement and was looking for a solution on the web.

I hope this helps other fellow learners like me. Please do let me know if I made a mistake, I'm just a newbie dev.

Have a good day ahead.

~ Pixel
