### ISSUE TITLE
Spotty 

### ISSUE THREAD

**Issue by Zarukei** [0x48piraj/fadblock#101]
About 80% of the time it will not block any ads and i have to refresh abbot 4 times before it plays the video.  I emailed the dev to let them know and was told to keep trying it and see how the changes are and it hasnt worked

**Comment by 0x48piraj** [comment]
I don't think I told you to keep trying, I issued the following notice,

Kindly refrain from using alternative ad blockers, especially if you've supported FadBlock through a donation. Some users combining multiple ad blockers, against the FAQ's advice, are facing detection issues, resulting in YouTube account bans. It's not a FadBlock issue in any way. It is working for people who are only using FadBlock.

Note: If YouTube has banned you, removing Adblocker Plus/Ultimate, uBlock won't work as YouTube has logged your IP, device and account data into their ban list.

Here's a Reddit thread that proves the above remark: https://www.reddit.com/r/Adblock/comments/17rluvd/purging_caches_refreshing_in_ublock_on_firefox/

See here, https://github.com/0x48piraj/fadblock/issues/88, https://github.com/0x48piraj/fadblock/issues/89, https://github.com/0x48piraj/fadblock/issues/87

Anyways, redirectinhg yo a similar thread (https://github.com/0x48piraj/fadblock/issues/103) which has detailed information to work with.
