### ISSUE TITLE
Ads are show

### ISSUE THREAD

**Issue by Daniel0389** [0x48piraj/fadblock#104]
Hello the am going to report the issue is the extensions of FadBlock: Friendly Adblock for Youtube™ could not work, when i playing the Youtube video it will have ads show 

Here is the photo
![Problem](https://github.com/0x48piraj/fadblock/assets/103320659/b5899db9-24a2-4321-9953-156a847b984c)

Thanks

**Comment by DavidChou23** [comment]
same issue

**Comment by cy-rick-lin** [comment]
Same issue here

**Comment by EC4U2CStudioz** [comment]
same issue on firefox

**Comment by SS20x3** [comment]
Same issue on Opera Gx, worked previously

**Comment by aleb117** [comment]
same problem

**Comment by AlecDiramerian** [comment]
same issue on chrome

**Comment by eason9709** [comment]
same problem on microsoft edge

**Comment by Meza85** [comment]
https://github.com/0x48piraj/fadblock/issues/103#issuecomment-1806711594

**Comment by firzenex96** [comment]
The Ads are show from yesterday too

**Comment by RafalGanowicz** [comment]
Ads showing on Firefox and Chrome.

**Comment by 0x48piraj** [comment]
**The new version (2.5) is out on Chrome! LFG!**
