### ISSUE TITLE
Not working on Firefox or Chrome for me.

### ISSUE THREAD

**Issue by MisterUnlikely** [0x48piraj/fadblock#105]
I donated to fadblock, and it stopped working for me on Firefox, so I decided to try it on Chrome (v 119).  It's not working there at all (no other adblocker extensions are in my Chrome, either).  I don't know if this is because Chrome sees me as a non-sponsor or not.  Please advise.

**Comment by ExplosionMEOW** [comment]
#103

**Comment by harkai84** [comment]
Hello, i use Version 120.0.6099.18 (Offizieller Build) beta (64-Bit) google chrome beta on Linux and it still works.

**Comment by 0x48piraj** [comment]
It's not dependent on donation.

I'm constantly working on it, here's yesterday's log: https://github.com/0x48piraj/fadblock/issues/103

A new version is underway, just wait for a few hours.

**Comment by 0x48piraj** [comment]
**The new version (2.5) is out on Chrome! LFG!**
