### ISSUE TITLE
country problem

### ISSUE THREAD

**Issue by eerrerer321** [0x48piraj/fadblock#106]
hello , 
I wanna pay 5.99USD for lifetime license, but my country Repubic of China is not in country list.
current country "Taiwan, Province of China" is wrong name.

**Comment by 0x48piraj** [comment]
That's a problem with the payment processor, I will try to contact them.

You can use Paypal: https://www.paypal.me/piyushella


Please update. **The new version (2.5) is out on Chrome! LFG!**
