### ISSUE TITLE
if the fadblock, which doesn't work can't automatically skip ads, we maybe consider to add a manual button?

### ISSUE THREAD

**Issue by myforself** [0x48piraj/fadblock#107]
the fadblock doesn't work automatically again. If you can, maybe you add a manual button to achieve an extremely brief timeframe for ads?

**Comment by ItsTepsu** [comment]
I think this is actually a really good idea. I haven't had any problems with ads being blocked so far, but I have seen a lot of people having trouble with it. A manual button would also just be fun to skip ads.

**Comment by 0x48piraj** [comment]
**The new version (2.5) is out on Chrome! LFG!**

It will start working again automatically, please update.

I think the idea is fun, but people will get tired of clicking "Skip". I can add one for beta testers or something, I will think about it!

**Comment by myforself** [comment]
> **The new version (2.5) is out on Chrome! LFG!**
> 
> It will start working again automatically, please update.
> 
> I think the idea is fun, but people will get tired of clicking "Skip". I can add one for beta testers or something, I will think about it!

I think the manual button will be a good spare choice because sometimes the fadblock doesn't work automatically and YouTube is too quick about their update. furthermore, I have an idea about the manual function. I think the fadblock must not need to load the data from the page as we scan the whole web. when we put the manual button, if the fadblock scans any ad element, it will start to achieve an extremely brief timeframe for ads. Do you think it will work?

**Comment by ItsTepsu** [comment]
> **The new version (2.5) is out on Chrome! LFG!**
> 
> It will start working again automatically, please update.
> 
> I think the idea is fun, but people will get tired of clicking "Skip". I can add one for beta testers or something, I will think about it!

I would love to see it for the next version because it would be nice to be able to manually skip if for some reason it fails to skip.
