### ISSUE TITLE
Fadblock no longer working

### ISSUE THREAD

**Issue by RafalGanowicz** [0x48piraj/fadblock#108]
At 12:00 CST today, the fad block no longer works. I have no extensions running Firefox 119.0.1 (64-bit).

Thank you,
Rafal

**Comment by PTAHume** [comment]
same here for YouTube, also dose not appear to fast forward on Chrome either anymore, guess YT have caught onto this same with all other ad blockers ;(

**Comment by potinghuang** [comment]
It can be expected. Google will fix it very soon.

**Comment by christian100kodehode** [comment]
Yes also see the ads here now, latest version 2.2 (payed) of course..

**Comment by eliezercazares** [comment]
I think it's only with 5 second ads, as those probably lack ff/skip controls...

**Comment by 0x48piraj** [comment]
**The new version (2.5) is out on Chrome! LFG!**
