### ISSUE TITLE
Potentially Does Not Skip Surveys

### ISSUE THREAD

**Issue by boulwabd** [0x48piraj/fadblock#11]
I'm not sure if this is unaccounted for in the content script (either unintentionally or by design) or was simply a one-off fluke but v1.1 appears to not skip user surveys prompted by Youtube. The survey in question did have a skip button. I didn't have time to check the HTML source for any new class names but will keep an eye out for the next one if it happens again.

Edit: Ok I finally caught another survey. It looks like  const skipLock is returning False because .ytp-ad-preview-text is not loaded during the survey. It does load the class .ytp-ad-survey though and still has the same .ytp-ad-skip-button class so perhaps including the survey class as an OR operand for skipLock will fix it. I am adding it to my local branch and will see how it goes.

**Comment by boulwabd** [comment]
![image](https://github.com/0x48piraj/fadblock/assets/16289725/543776bd-81d8-4d11-8bee-58536fc06a6a)

**Comment by 0x48piraj** [comment]
I'm pushing a dev build with the patch, can you install manually via [releases](https://github.com/0x48piraj/fadblock/releases) and see if it works?
