### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by xinranliu7** [0x48piraj/fadblock#110]

**Comment by blurskye** [comment]
paid what?

**Comment by xinranliu7** [comment]
the lifetime access 5.99 but still cannot skip ads

**Comment by xinranliu7** [comment]
How can I get a refund?

**Comment by blurskye** [comment]
bro there is no pro/lifetime plan, wtf, how did you manage to get scammed?, there never was a paid plan
![image](https://github.com/0x48piraj/fadblock/assets/145671529/767935fb-abba-424e-b01f-44e1aaeb10fd)

**Comment by blurskye** [comment]
@xinranliu7 check above comment

**Comment by xinranliu7** [comment]
?

Please explain?

I did not get scam, on the page it says pay 5.99 to get a lifetime or
whatever then I clicked it paid but it won’t work.

I call the bank.

This sucks lol.

Anyone who’s seeing this please don’t use it.

**Comment by blurskye** [comment]
there is no paid option, there never was, you just got scammed buddy, next time, careful what you buy
open source projects dont usually ask for pro membership

**Comment by blurskye** [comment]
@xinranliu7 i think some scammer is using this project to get money out of ppl, there never was a paid option, use headover to 
https://github.com/0x48piraj/fadblock
https://chromewebstore.google.com/detail/fadblock-friendly-adblock/mdadjjfmjhfcibgfhfjbaiiljpllkbfc
to check out the real project, and let us know how and where you downloaded the extention from, lol

**Comment by xinranliu7** [comment]
can you even see the attached pic said check card fadblock???

Every time I I clicked on the fadblock sign there’s a pay sign there. I did
spend long time consider whether to pay it or not and you make it sound
like I’m a careless person. Either I got scammed by you or you let this
thing happen. Either way this is mostly your fault! And, there could be
more people got scammed just like me. Therefore, I don’t see this is
anything funny or you can take it easy and be buddy buddy with me. Because
of this I’m going to replace my bank card. Such a disappointment!

AGAIN, DO NOT USE THIS!

**Comment by Lars4k** [comment]
![image](https://github.com/0x48piraj/fadblock/assets/76779612/20626e45-c869-4a16-b996-28a44e913885)

**Comment by christian100kodehode** [comment]
You have to pay to use this extension,, the free version just blocks a few videos.. Its written all over the app site.. Just read the readme .. https://github.com/0x48piraj/fadblock#faq You did the correct thing xinranliu7 !!

I have seen it getting some issues not skipping all the videos now, but i look forward to another update soon!

**Comment by zolexander** [comment]
The extension works for me only in Inkognito mode, without any Youtube account logged in.   I don't think to pay for  a license, make any difference. I reinstalled Firefox and deleted the browser cache,even I deleted the  whole ".mozilla" directory.

**Comment by arjanvlek** [comment]
> ![image](https://user-images.githubusercontent.com/76779612/282452172-20626e45-c869-4a16-b996-28a44e913885.png)

@xinranliu7 and @Lars4k Welp, that seems to be a scam extension. The original should look like this:

![Scherm­afbeelding 2023-11-13 om 14 34 20](https://github.com/0x48piraj/fadblock/assets/10106652/87768692-585c-443f-a40a-47c7bca3509c)

Btw, this one is also broken, but that's already discussed in #108

**Comment by xinranliu7** [comment]
Lol, mine look exactly like the second one.

Btw, looks like the scammers team thinks that this plug-in only worth
5.99$😂 for a lifetime.

Also, stop replying if you’re not trying to help.

**Comment by zolexander** [comment]
After You blocks over 50 Ads, the text changes. For the "Get Lifetime License" for $5.99. So this is not scam. I saw it in the Firefox.

**Comment by christian100kodehode** [comment]
It is clearly stated in the readme.... Its 5.99 for the license...

**Comment by ManuTester** [comment]
The payment is just a way to support the poor developer, especially now that he has a lot of work adapting to google's changes. Paying does not change the functionality in any way.
Currently it does not work, sadly.

**Comment by eliezercazares** [comment]
I think it's only with 5 second ads, as those probably lack ff/skip controls...

**Comment by ManuTester** [comment]
Nope, sorry to say, doesn't work at all at the moment, at least for me. I even tried the Chrome plugin to rule out any weirdness with my firefox (actually waterfox). No cigar, Youtube behaves absolutely the same with and without the plugin.

**Comment by zolexander** [comment]
The Firefox extension works in Incognito tabs, when you aren't logged in. At least that's works, but the Mutation Observer makes slower the site. In normal tabs does'nt work that's true. I don't understand why. I tried many things.
The chrome extension has some issue with a null value. 
`Can't read of property of null .arrive(`
I hope that can help the developer.

**Comment by 0x48piraj** [comment]
Thank you for chiming in @christian100kodehode. It was a great help, but I suggest to not spend your important time to these spam comments. I have learned the hard way.

To the ones who know I'm the developer and no "scammer" puts the software over GitHub and attaches his online identity to the project.

**The new version (2.5) is out! LFG!**

**Comment by 0x48piraj** [comment]
As for you Mr. @xinranliu7, I checked the ledger and there's no record for `1904493873@qq.com`.

If you really paid, you would have gotten a receipt as well as my email for contact in case any problem occurs.

Just update to the newest version and enjoy using it for free. If you really paid, email me with your real payment details and I will be happy to fix your problem.

Hell, I just added added your email for free as a lifetime member, enjoy.

Just don't call me a scammer, they earn in millions lol (and they are bad people, hmm, I should have started with that).

**Comment by xinranliu7** [comment]
Please see the pictures above.

**Comment by arjanvlek** [comment]
I'm really sorry for calling the paid version a scam. I honestly wasn't
aware of the changes in version 2.0, which I've now seen in the readme.

Op di 14 nov 2023 om 08:10 schreef xinranliu7 ***@***.***>:

**Comment by 0x48piraj** [comment]
I am sorry but you haven't posted any pictures @xinranliu7. Don't worry about it, just use that email to login, I hope it works, feel free to create an issue again if it stops working and I will update it quickly as this new version has an inbuilt backend where it fetches the latest patch details.

**Comment by xinranliu7** [comment]
Hi, @0x48piraj 

Thanks for your help. Earlier, I was confused and mistook some random guys who told me I was being scammed for the real developers. (I thought I was being gaslighted by the development team, lol...)

I'm really grateful for the lifetime membership, and I believe you deserve my payment because this plugin is very helpful. I also paid for it even when it wasn't working.

Sorry for any confusion that may have caused you trouble. I've deleted the incorrect statements I made about you, as I thought I was communicating with the real developer at the time, and none of those comments were directed towards you.

P.S. I've attached pictures of my receipt for your reference.
![IMG_5648](https://github.com/0x48piraj/fadblock/assets/144504912/c199dd08-f13a-4a8f-9b05-8b12415a2673)
![IMG_5649](https://github.com/0x48piraj/fadblock/assets/144504912/77d6773b-4b51-4dc0-87b9-75af8273b815)

**Comment by 0x48piraj** [comment]
There's my email, no? You should have contacted,

That's probably a transaction that failed the first time so it went unprocessed and then got processed at a later date because I wasn't able to see it, also, if you weren't able to log in, that clearly means the transaction didn't go through.

I hoped you were a decent person because you at least reached out to the Issues rather than just slandering over reviews and not responding so it's all good.

I would suggest you delete the screenshots now because it has email details as well as some sensitive info. I can verify

**Comment by xinranliu7** [comment]
> There's my email, no? You should have contacted me.
> 
> That's probably a transaction that failed the first time so it went unprocessed and then got processed at a later date because I wasn't able to see it, also, if you weren't able to log in, that clearly means the transaction didn't go through.
> 
> I hoped you were a decent person because you at least reached out to the Issues rather than just slandering over reviews and not responding so it's all good.
> 
> I would suggest you delete the screenshots now because it has email details as well as some sensitive info.

Actually, I did receive this email a bit later, so it was all a misunderstanding.

Also, could you delete this issue? I couldn't delete it from my side.

**Comment by 0x48piraj** [comment]
Sure. Closing.
