### ISSUE TITLE
Will Paypal work to pay the $5.99?

### ISSUE THREAD

**Issue by EC4U2CStudioz** [0x48piraj/fadblock#112]
Will PayPal be accepted to pay the one-time $5.99 support fee?  If people choose to pay the $5.99, Paypal should be an option for payment.

**Comment by Tmdoofking** [comment]
don't pay that a scam, you download scam one

**Comment by Tmdoofking** [comment]
#110

**Comment by christian100kodehode** [comment]
A scam ? You have not been using this extensipon and seen the readme ? https://github.com/0x48piraj/fadblock#faq

(As this project has demanded a substantial amount of time, the repository will transition to an open-core model for ongoing maintenance and updates.

Note: Some people are getting confused about the new permissions as well as the access to extensionpay.com. The storage permission is for counting the "Blocked YouTube Ads" and ExtensionPay is a payment processor integrated with [Stripe](https://stripe.com/en-in) for obtaining a lifetime license after an initial free trial period (it's gonna stay free after as well but will ask for a contribution every now and then).)

**Comment by 0x48piraj** [comment]
Thank you for chiming in @christian100kodehode. It was a great help, but I suggest to not spend your important time to these spam comments. I have learned the hard way.

To the ones who know I'm the developer and no "scammer" puts the software over GitHub and attaches his online identity to the project.

**The new version (2.5) is out! LFG!**

**Comment by 0x48piraj** [comment]
As for @EC4U2CStudioz, it will work regardless, it's your choice whether to pay or not. Update to the newest version and see if it works. Closing.
