### ISSUE TITLE
On Fadblock

### ISSUE THREAD

**Issue by TgZ39** [0x48piraj/fadblock#113]
![85wu22](https://github.com/0x48piraj/fadblock/assets/71944761/3f3253ca-2182-42fb-8b92-af849b795b4f)

**Comment by 0x48piraj** [comment]
Good meme, you should know that YouTube team is updating constantly while I have to wait for the Chrome and Firefox dev team to complete their review process and publish the new version.

I hope you looked at #103 before posting this but oh well, good content is good content!

By the way, be sure to check out the new version...and make another meme if that too doesn't work out! Cheers!

**Comment by 0x48piraj** [comment]
If it's working fine for you @TgZ39, feel free to close the issue, or I can do it. I'll step back for a while, so others can have a good laugh ;)

**Comment by TgZ39** [comment]
> Good meme, you should know that YouTube team is updating constantly while I have to wait for the Chrome and Firefox dev team to complete their review process and publish the new version.
> 
> I hope you looked at #103 before posting this but oh well, good content is good content!
> 
> By the way, be sure to check out the new version...and make another meme if that too doesn't work out! Cheers!

Do you think that your adblocker will always find a way to skip ads, or can YouTube to make it impossible to skip them?

**Comment by 0x48piraj** [comment]
I think I have done a pretty good job this time, thanks to the donations, the new version includes a built-in server that FadBlock uses to fetch the new patch info for quicker releases.

If all goes well, FadBlock from here and out will stop for like an hour or two when a new patch launches and will fetch the new patch and start working again instantly.

**Comment by PatFat8r14u4** [comment]
> Good meme, you should know that YouTube team is updating constantly while I have to wait for the Chrome and Firefox dev team to complete their review process and publish the new version.



Just a noob in CS. 
How do you know the inside content of the Chrome dev team or YT team release patches? (VERY CURIOUS)
You mentioned at #103 that "The new YT patch delays the readyState". But How do you know the YT patch delays it?


Many Thanks for updating FADblock!

**Comment by eliezercazares** [comment]
> Good meme, you should know that YouTube team is updating constantly while I have to wait for the Chrome and Firefox dev team to complete their review process and publish the new version.
> 
> I hope you looked at #103 before posting this but oh well, good content is good content!
> 
> By the way, be sure to check out the new version...and make another meme if that too doesn't work out! Cheers!

Hi man, thanks a lot for your support to us. 
I see a lot of ungrateful comments... but anyway.... let them be..

My question is... will the update you just did apply also to the free version of fadblock?

**Comment by cnekmp** [comment]
> Good meme, you should know that YouTube team is updating constantly while I have to wait for the Chrome and Firefox dev team to complete their review process and publish the new version.

Release compiled extensions so impatient users could download it from github and install them manually for their browsers (at least Firefox, I don't use Chrome, so no idea about that)?

**Comment by christian100kodehode** [comment]
Btw I still only see v2.2 as last version (firefox)... And the update log might trigger such memes:

"- Increased the ask-for-contribution popup frequency by 1566.67%"

**Comment by 0x48piraj** [comment]
@PatFat8r14u4, I can talk to the Chrome dev team as I am publishing the extension, also, you can see over the developer dashboard. About the YouTube patches, it's... reading the client source (>4mb), sending requests, analyzing responses, and in general, doing a lot of black box reverse engineering.

**You're doing great!** Diving into threads and making an effort to comprehend things is an excellent initial step.

@eliezercazares, of course, all updates, will happen without discrimination, it's not a paid version, it's just an ask for donations. The functionality will remain the same, that's why a small popup for the free users to hopefully nudge them into donating as when you don't ask for donations profusely, you don't get any, at all. That's the sad reality.

@christian100kodehode, the update log was actually meant to be an inside joke (from 3 to 50 = 1500% increase), thank god someone noticed it!

As for the update goes, Firefox Store hasn't published the extension since 11th Nov. The dev team isn't responding as well.

![image](https://github.com/0x48piraj/fadblock/assets/5800726/b2c78bc3-fe9b-494e-a06e-ddd2a8a49f08)

FadBlock over Firefox faced quite a storm of trolls with name-calling, reports, and everything in between. Looks like they're facing the consequences now.

**Comment by eliezercazares** [comment]
> @PatFat8r14u4, I can talk to the Chrome dev team as I am publishing the extension, also, you can see over the developer dashboard. About the YouTube patches, it's... reading the client source (>4mb), sending requests, analyzing responses, and in general, doing a lot of black box reverse engineering.
> 
> **You're doing great!** Diving into threads and making an effort to comprehend things is an excellent initial step.
> 
> @eliezercazares, of course, all updates, will apply to everyone without any discrimination, it's not a paid version, it's just an ask for donations. The functionality remains the same for everyone, that's why a quick popup time-to-time for the free users to _hopefully_ nudge them into donating as when you don't ask for donations profusely, you don't get any, at all. That's the sad reality.
> 
> @christian100kodehode, the update log was actually meant to be an inside joke (from 3 to 50 = 1500% increase), thank god someone noticed it!
> 
> As for the update goes, Firefox Store hasn't published the extension since 11th Nov. The dev team isn't responding as well.
> 
> ![image](https://user-images.githubusercontent.com/5800726/283068399-b2c78bc3-fe9b-494e-a06e-ddd2a8a49f08.png)
> 
> FadBlock over Firefox faced quite a storm of trolls with name-calling, reports, and everything in between. Looks like they're facing the consequences now.

Thank you brother.

One last question, do you think the extension could be delivered by email and installed locally? Or do we have to wait for Mozilla team to review the extension and approve it? 

If I'm willing to give away my privacy it won't be to Google xD

**Comment by TgZ39** [comment]
joe mama

**Comment by TgZ39** [comment]
remov da premium spam
