### ISSUE TITLE
Does not work, even with "Newest version"

### ISSUE THREAD

**Issue by HastyRhombus760** [0x48piraj/fadblock#114]
Title says it all. I use Opera and this "blocker" does nothing at all.

**Comment by ItsTepsu** [comment]
Make sure you have Opera/OperaGX's ad blocker disabled, as well as  any other extensions that might cause the ad blocker to not work. 

My best suggestion is to disable everything except fadblock and see if anything is causing problems.  I user OperaGX and it works perfectly fine (Version 2.5)

**Comment by Toxella** [comment]
Another opera user here, same thing started happening to me a few days ago. All extensions disabled except the latest FadBlocker version, still receiving youtube ads.

**Comment by ItsTepsu** [comment]
> Another opera user here, same thing started happening to me a few days ago. All extensions disabled except the latest FadBlocker version, still receiving youtube ads.

I'd try and help further, but I'm not associated with the developer, and I don't know enough about how it works either. Best thing I can suggest is to make sure opera is up to date, and try reinstalling the extension.

**Comment by Rynn21** [comment]
On Firefox, only fadblock running, and ads come right through now. Fadblock also horribly slows down browsers.

**Comment by zolexander** [comment]
Firefox: in the  Firefox Store  still the 2.2 Version  is online. It works unfortunately  not so well, the MutationObserver  slows down browser. The 2.5 Version(the last) works without any problem, and I did'nt have any ads -since I installed it).

**Comment by ItsTepsu** [comment]
> Firefox: in the Firefox Store still the 2.2 Version is online. It works unfortunately not so well, the MutationObserver slows down the browser. The 2.5 Version(the last) works without any problem, and I did'nt have any ads -since I installed it). It takes some time, until globally everybody gets the new version. Sometimes Chrome Store faster, last time the Firefox Store was faster.

Make sure the update isn't available. It might need to be manually installed.

For the opera users, check to make sure you don't need to update it manually. If that doesn't work try uninstalling the extension and reinstalling it.

**Comment by 0x48piraj** [comment]
Thank you @zolexander for helping out.

Firefox Store hasn't published the extension since 11th Nov. The dev team isn't responding as well.

![image](https://github.com/0x48piraj/fadblock/assets/5800726/b2c78bc3-fe9b-494e-a06e-ddd2a8a49f08)

Firefox faced quite a storm of trolls with name-calling, reports, and everything in between. Looks like they're facing the consequences now.

**Comment by MrDrDevil** [comment]
chrome user here
starts receiving YouTube ads, from this morning
uninstalled & reinstalled 
still facing the same issue
15/11/23
![Screenshot (936)](https://github.com/0x48piraj/fadblock/assets/134045207/15c5a8b7-a1c8-46f4-81b2-ad55852adb65)

**Comment by MrDrDevil** [comment]
chrome user here
starts receiving YouTube ads, from this morning
uninstalled & reinstalled
still facing the same issue
15/11/23
![23](https://github.com/0x48piraj/fadblock/assets/134045207/5c299659-ba95-4b58-812a-1aba17b1b57e)

**Comment by Grg76** [comment]
Now V2.5 is published on Firefox too

**Comment by Grg76** [comment]
> Firefox Store hasn't published the extension since 11th Nov. The dev team isn't responding as well.


Now it's published for Firefox too

**Comment by 0x48piraj** [comment]
@MrDrDevil, can you put `chrome://extensions` onto the address bar and send the screenshot?

**Comment by zolexander** [comment]
This version of the fadblock is old. The newest one is the 2.5 which available in the store: 
Uninstall the 1.3 Version and install this:.
https://chromewebstore.google.com/detail/fadblock-friendly-adblock/mdadjjfmjhfcibgfhfjbaiiljpllkbfc?utm_source=ext_app_menu
The Adguard Adblocker: you might should  add youtube.com to whilelist, and after this, should work.

**Comment by MrDrDevil** [comment]
oh ok ...i will do it right now...and let you the result

thank you

**Comment by Revemohl** [comment]
I just got a mid-roll ad while watching a livestream after having updated to 2.5, using Firefox. I guess it's still not 100%.

**Comment by eliezercazares** [comment]
> Make sure you have Opera/OperaGX's ad blocker disabled, as well as any other extensions that might cause the ad blocker to not work.
> 
> My best suggestion is to disable everything except fadblock and see if anything is causing problems. I use OperaGX and it works perfectly fine (Version 2.5)

Could it be that youtube is obfuscating the CSS/HTML Locators for the Ads? 
I created a Feature Request explaining a possible way around this, at least temporarily.

**Comment by zolexander** [comment]
It's not obfuscating. What they do, the source code of the page suddenly changes. They began to use JavaScript based style changes: even adding empty  "display:none" elements.  There is in the page  an iframe from  src= "about:blank",  which don't make any sense. The entire YouTube source code became  very complicated.  It better, then obfuscation.   Not everybody has the same site. They can locally generate other YouTube pages experiment which is the best against Adblockers.

**Comment by eliezercazares** [comment]
> It's not obfuscating. What they do, the source code of the page suddenly changes. They began to use JavaScript based style changes: even adding empty "display:none" elements. There is in the page an iframe from src= "about:blank", which don't make any sense. The entire YouTube source code became very complicated. It better, then obfuscation. Not everybody has the same site. They can locally generate other YouTube pages experiment which is the best against Adblockers.

We need to act maybe at OS level, by identifying ad servers we can act directly on the video player at OS level to FF ?

**Comment by zolexander** [comment]
There is a little bit problem with the concept: the ad itself is on the youtube.com
The video element: src attribute is some blob with src="blob:https://youtube.com/{some_guid}

I think this solution of @0x48piraj is good enough.

**Comment by eliezercazares** [comment]
> There is a little bit problem with the concept: the ad itself is on the youtube.com The video element: src attribute is some blob with src="blob:[https://youtube.com/{some_guid}](https://youtube.com/%7Bsome_guid%7D)
> 
> I think this solution of @0x48piraj is good enough.

I have v1.3 on FF and it's not working since a few days ago, 1 or 2.

Did you check the code? He literally checks for the existance of CSS attributes. I will do my testing and let you know, I just have to look for that CSS he looks for when an ad is shown.

**Comment by zolexander** [comment]
Yes, I read the code, even of the last version. Its not  difficult. Only try to find where is the video element and with some css classes, decides when to ad escape.

**Comment by eliezercazares** [comment]
> There is a little bit problem with the concept: the ad itself is on the youtube.com The video element: src attribute is some blob with src="blob:[https://youtube.com/{some_guid}](https://youtube.com/%7Bsome_guid%7D)
> 
> I think this solution of @0x48piraj is good enough.

Yeah but it seems you have problems following that the extension is not working...
But... Ok, I did my testing looking for the css values while an ad is shown and in my case, all the CSS elements were found, however it's not skipping... 

```
 const isAd = videoContainer?.classList.contains("ad-interrupting") || videoContainer?.classList.contains("ad-showing");
      const skipLock = document.querySelector(".ytp-ad-preview-text")?.innerText;
      const surveyLock = document.querySelector(".ytp-ad-survey")?.length > 0;

      if (isAd && skipLock) {
        const videoPlayer = document.getElementsByClassName("video-stream")[0];
        videoPlayer.muted = true; // videoPlayer.volume = 0;
        videoPlayer.currentTime = videoPlayer.duration - 0.1;
        videoPlayer.paused && videoPlayer.play()
        // CLICK ON THE SKIP AD BTN
        document.querySelector(".ytp-ad-skip-button")?.click();
        document.querySelector(".ytp-ad-skip-button-modern")?.click();
      } else if (isAd && surveyLock) {
        // CLICK ON THE SKIP SURVEY BTN
        document.querySelector(".ytp-ad-skip-button")?.click();
        document.querySelector(".ytp-ad-skip-button-modern")?.click();
      }

```


Now I am wondering if we need .volume instead, and concerned a bit that maybe .duration attribue was disabled... but in this case the author could use another value instead of videoPlayer.duration as he is doing:

```
        videoPlayer.muted = true; // videoPlayer.volume = 0;
        videoPlayer.currentTime = videoPlayer.duration - 0.1;
```

It could be:

```
        videoPlayer.muted = true; // videoPlayer.volume = 0;
        videoPlayer.currentTime = document.querySelector(".ytp-ad-preview-text")?.innerText
```


I am leaving those comments mostly for the author. But if you have something to contribute I will be glad to look at your code or test results.

**Comment by zolexander** [comment]
It's not better for you to download the 2.5 Version? It's available from the store. He found the solution, even he commented about this.

**Comment by eliezercazares** [comment]
> It's not better for you to download the 2.5 Version? It's available from the store. He found the solution, even he commented about this. I don't want to open his solution, because this became half "open-source" project, but I am sure about this. In the Mozilla/Chrome Store, there is the source code of the last extension.

bruh, it was me. my bad.

I just downloaded 2.5 and it works XD

I was desperate.

thanks again!

**Comment by francogrex** [comment]
> Title says it all. I use Opera and this "blocker" does nothing at all.

Same for Chrome. Not blocking any adds, although installation is all fine.

**Comment by 0x48piraj** [comment]
@MrDrDevil, I asked because most people are not reading the FAQ and stacking adblockers onto adblockers. Just like what you were doing, and that makes the problem difficult. If YouTube finds a way to detect ABP or uBlock which they did a week ago, blocked user accounts, users will confuse that with FadBlock, same with the black screen issue, it only happens with the traditional adblockers, not FadBlock.

@francogrex, read the announcement, as the codebase grew and YouTube started implementing complicated techniques as DOM manipulation as @zolexander promptly discussed, it was better they can't readily see the CSS elements I look for and change them frequently causing more work as well as the reasons I discussed in the announcement.
