### ISSUE TITLE
For Chrome Users

### ISSUE THREAD

**Issue by Frammer** [0x48piraj/fadblock#115]
2.5 is working well, 2.2 is not working anymore.
The problem lied in that it was not automatically downloading the latest version of the extension.

The github repository here is a few versions behind, so I was unable to find it.

There was no "download latest version" on the store page.

What I had to do was remove it on the store page, then add it back, and it downloaded the latest version (2.5)

Be careful though, if you have any YouTube pages open, it will start playing all the videos.

**Comment by ItsTepsu** [comment]
**Manually Reinstall the Extension!**

Version 2.5 is out on the Chrome Web Store. If it isn't updating, try reinstalling it again. It worked for me.

**Comment by seebeedub** [comment]
Mine updated to 2.5 on Chrome without me doing anything special and it worked as expected! First time in quite a few days. Thanks for your efforts!

**Comment by 0x48piraj** [comment]
That's the intended function, Chrome auto-updates the versions after 24 hours but can fail sometimes, just reinstall and it should work.

If it still doesn't (v2.5) please post the issue with the DOM state so I can look into it. Closing.
