### ISSUE TITLE
Fadblock crashes opera gx

### ISSUE THREAD

**Issue by Momossim** [0x48piraj/fadblock#116]
when i try to load it, opera gx just crashes. It may be my fault idk but i followed the guide

**Comment by Momossim** [comment]
> How are you loading the extension?
> 
> I would suggest you use this [Opera blog](https://blogs.opera.com/tips-and-tricks/2021/10/using-addons-from-chrome-in-opera/) to sideload FadBlock v2.5 Chrome extension to your browser.

i was using the opera method

**Comment by Momossim** [comment]
> How are you loading the extension?
> 
> I would suggest you use this [Opera blog](https://blogs.opera.com/tips-and-tricks/2021/10/using-addons-from-chrome-in-opera/) to sideload FadBlock v2.5 Chrome extension to your browser.

i checked the link, and the extension dosent exist anymore; but if i try to download fadblock from chrome web store, it dosen't work either (it says "Download interrupted with reason: SERVER_BAD_CONTENT")

**Comment by 0x48piraj** [comment]
Ah, okay I will look into that.

**Comment by fbit-itc** [comment]
same here , SERVER_BAD_CONTENT
(N.B. the 'load-chrome-extension-extension does not exist anymore because it's been integrated in opera since year or so....)

**Comment by Momossim** [comment]
hey btw the "server_bad_content" isnt your fault, it's doing it even with like google translate

**Comment by Momossim** [comment]
ok this is ridiculous i tried to download an extension from the opera store and it (opera gx) crashed

**Comment by Momossim** [comment]
ok big thing: the extension works if i download the chrome one, but crashes with the opera one. i understand absolutely nohting.
@0x48piraj @fbit-itc tldr: use the chrome one idk why

**Comment by Momossim** [comment]
ok you can install the chrome one but it dosen't work (i got ads)

**Comment by 0x48piraj** [comment]
2.6 working consistently, closing.

**Comment by Momossim** [comment]
I don't find how to download the 2.6 version, only the 1.3 and before

**Comment by Momossim** [comment]
> I don't find how to download the 2.6 version, only the 1.3 and before

I installed the 2.6 version by downloading the zip extension from the chrome web store, then unpacking it and it seems to work.
