### ISSUE TITLE
Doesn't mute the first ad

### ISSUE THREAD

**Issue by owaisali10** [0x48piraj/fadblock#12]
videoPlayer.muted = true; does not work for the first ad (works for the second ad that follows). I believe it's because this code really starts working after 100 ms. 

I'm not sure if there is a workaround to this. But could you please look into this? Thanks.

**Comment by Rapha149** [comment]
I have the problem too, but for me both ads are not muted.

**Comment by 0x48piraj** [comment]
The upcoming version will utilize a custom `MutationObserver` with a polyfill to ensure compatibility with older browsers which hopefully will solve this issue.
