### ISSUE TITLE
[Solved temporary] It's now skipping whole video sometimes.

### ISSUE THREAD

**Issue by littlemeh** [0x48piraj/fadblock#122]
Sometimes it stuck at the beginning of the video, and it looks like it's refreshing the videos for a couple times, then it just skip the whole video. If I refresh the same video, it will still happen, but doesn't happen on all the video. And if I jump back and start the video, not from the beginning, I will be able to watch the video, but it will not have any volumn. The browser I used is Brave.

**Comment by diego10arg** [comment]
I am facing the same issue, running on Chrome Version 119.0.6045.160 (Official Build) (64-bit)

With this video, for example: https://www.youtube.com/watch?v=6VbyXDn6ZzA

**Comment by yoniwulf** [comment]
I also have the same issue

**Comment by 0x48piraj** [comment]
This seems very weird, I got similar reports, let's move to (https://github.com/0x48piraj/fadblock/issues/125). Closing.
