### ISSUE TITLE
Fadblock on Safari: Zero Effect

### ISSUE THREAD

**Issue by Zayngster** [0x48piraj/fadblock#123]
I followed each step listed under the instructions for setting up Fadblock on safari and nothing at all has changed whatsoever. I disable my other ad blockers and disabled pdfs to auto-open in chrome. No changes. Idk if this is a current or previous issue, but I want help. 

I literally only care about ad blocking as it pertains to YouTube and while chrome's works, the website is still throttled as a result. I am on a MacBook Air so I know that alone causes quality issues at points, but the safari steps yielded zero changes for the issue at hand: YouTube ads.

**Comment by Rinfore** [comment]
YouTube made some changes recently that stop the mechanism fadblock was using. There are newer versions, but it seems they are not available for Safari. Would like to know how we can get a version for Safari, with any necessary contributions

**Comment by 0x48piraj** [comment]
The Safari version is outdated unfortunately and as the codebase got updated, Safari support was stopped.

I would request you to use Chrome for the time-being while the current codebase stabilizes.
