### ISSUE TITLE
Youtube ads gone now ads from Fadblock is showing

### ISSUE THREAD

**Issue by lianglee** [0x48piraj/fadblock#127]
Ads from fadblock is showing again and again asking for donation.

**Comment by RazaZaidi2802** [comment]
And they're quite consistent too. On every page.

**Comment by lianglee** [comment]
> And they're quite consistent too. On every page.

Yes i closed it and then appearing each time on every reload.

**Comment by SakarDev** [comment]
It's insane! I'm gonna remove it now ;(

**Comment by PNoveOfficial** [comment]
Fuck this dude. Mercenary asshole piece of shit

**Comment by PNoveOfficial** [comment]
He tries to fix the problem creating the same problem

**Comment by ItsTepsu** [comment]
As far as I know if you uninstall and reinstall the extension, it should reset it to stop showing the popup.

**Comment by civilmaddog420** [comment]
Why does this jerk have to break the functionality to supply an alternative advertisement now? Why would this asshole not create another problem to pay for some 'solution' some time later?

**Comment by 0x48piraj** [comment]
\*Takes a deep breath\*

Google is a company, and if you don't know, they have 174,014 employees if we believe this [source](https://www.doofinder.com/en/statistics/how-may-employees-does-google-have).

I am not breaking anything, and if you had more than two brain cells, any reasonable person would refrain from such actions, they would put a hard paywall for you people, not break their own extension intentionally, it's just bad marketing.

I am doing 1-v-174014 with Google, they are constantly changing their code, trying to shut out other adblockers, and they release geo-specific patches which in turn make the whole cat-and-mouse game harder.

I would have been so happy if you had looked around other issues to know what's happening and overall learn how any decent human being should behave, but oh well.

For those who are genuinely troubled, a new version has been submitted to the web store. Now we wait for the release. Other than the fix, an "update to latest" button was also added for fetching the latest patches from the in-built backend.

![image](https://github.com/0x48piraj/fadblock/assets/5800726/67d91d78-82d5-4d32-bd3f-730fe11aeaee)


For those using profane language, _Sarabada_.

**Comment by PNoveOfficial** [comment]
Nope. You are not the only one, this is not the only extension that does it, you are NOT special. Donating is ok, but asking for it does not need to be intrusive that way, shithead

**Comment by LukeSaward1** [comment]
Every fucking page, man.
And you can't even block it with Brave's bult-in element blocker.
Absolutely dogshit addition.

**Comment by LukeSaward1** [comment]
Every single page and it's not possible to block with any built-in element blocker.
For fuck sake, this is how every extension like this falls flat on its ass.

**Comment by 0x48piraj** [comment]
There's a bug that is causing the counter to go overboard more often than not. The new update will fix the issue, hopefully.

Do you guys know uBlock was acquired by ABP and the founder made millions, walked away, and restarted the project as uBlock Origin, so-called "completely free, no popups, etc."? Not every developer has this privilege so they ask for donations to justify all the time investment, or they just hard-paywall the entire thing, and do you know when developers ask for donations silently, they don't get a single donation?

And, I am not speaking just from the case studies, first month was just a small PayPal button, and not a single soul donated.

Literally, it's one popup after blocking 50 successful in-video ads, not to mention countless in-feed static ads. Just cancel away if you don't want to donate 6 bucks once, don't bitch and moan about it.

**Comment by LukeSaward1** [comment]
Asking for donations is fine. If you ask for donations on **every single page**, however, you end up seeming like you're begging and it's just _really_ fucking annoying to the user. We wouldn't bitch and moan about it if there was a way to disable it, which there isn't.

**Comment by gorhill** [comment]
> Do you guys know uBlock was acquired by ABP and the founder made millions, walked away, and restarted the project as uBlock Origin, so-called "completely free, no popups, etc."?

False, you are making up stuff. I never made a penny, let alone "millions". See <https://en.wikipedia.org/wiki/UBlock_Origin#uBlock>.

**Comment by PNoveOfficial** [comment]
"My name is piraj, I like to change de subject because I'm a retarded with half a brain"

> There's a bug that is causing the counter to go overboard more often than not. The new update will fix the issue, hopefully.

That's the only thing we were talking about. We don't care about how many employes Google have or lies about uBlock. Thank you

**Comment by 0x48piraj** [comment]
@gorhill, I referenced from the same wiki, which states that ublock.org was acquired by AdBlock. You then distanced yourself and forked the project as uBO. It's a bit tough to believe that when the project you created was acquired, there was nothing to receive.

I appreciate your initiative in restarting the project, and I harbor no ill feelings towards you. In various discussions, I consistently advocate for using uBO if you know what you are doing. In contrast, FadBlock is essentially a sophisticated auto-clicker—nothing more. However, comparing this project directly to a well-established one with a lengthy history and hundreds of maintainers seems unjust. On the flip side, FadBlock is the first project that gained a bit of traction when I just got out of college and it's just a matter of not being able to invest a lot of free time but people keep comparing this project to uBO.

**Comment by 0x48piraj** [comment]
@PNoveOfficial, calling me a retard after making FOUR edits on what seems like a two-liner. Ironic.

Please utilize uBO, as I have repeatedly said on the forums, over Reddit, and elsewhere, use uBO, just read their instructions/updates. uBO will be the default adblocker for everything after Google stops this nonsense.

But if you decide to use this tool, I am not capable of maintaining this project without any monetary incentive, and a donation remainder is fair in my opinion, if you don't agree, again, switch to uBO, it's better in every way imaginable. Just don't compare FadBlock to uBO, that's not fair, for both of us.

**Comment by LukeSaward1** [comment]
Yet you had to be corrected TWICE, once even by the CREATOR of uBlock Origin. You have no right to criticize others for mistakes or anything of the sort lmfao

**Comment by 0x48piraj** [comment]
@LukeSaward1, did you not see @PNoveOfficial personally attacking me?

As I said, I just made sense of what I read over wiki, and the fact that Hill had to personally come over here to clarify this, is devastating, I don't feel good about it at all.

@gorhill, I did, over https://github.com/0x48piraj/fadblock/issues/42#issuecomment-1790175140. By millions, I meant the revenue AdBlock makes and made a generous assumption about how an acquisition by such a company can provide plenty of financial freedom to the original creator. I don't think over wiki, it's written you forked the project years before, and overall the whole acquisition of both products (uBlock and AdBlock) was shrouded in mystery, [Adblock extension with 40 million users sells to mystery buyer, refuses to name new owner](https://thenextweb.com/news/trust-us-we-block-ads), [The AdBlock Family Gets a New Addition](https://blog.getadblock.com/the-adblock-family-gets-a-new-addition-62a887d36960) and many more articles do not clarify on how things went down.

I did not spread misinformation about uBO, but I am sorry for assuming things that weren't right, in my defense, the timeline is so very complicated, it just made sense.

_Although..._ seems like uBO also doesn't like seeing its alternatives, https://github.com/0x48piraj/fadblock/issues/131#issuecomment-1819226542. Just kidding. I won't be discussing the acquisition of uBlock or uBO timeline, only recommending that more people give it a try.

**Comment by LukeSaward1** [comment]
Sure, saying 'retard' is bad, but the claim about lies/misinformation cannot really be refuted when you have the creator of uBlock Origin backing the claim up.

**Comment by gorhill** [comment]
> I did not spread misinformation about uBO

You did (_"uBlock was acquired by ABP and the founder made millions, walked away, and restarted the project as uBlock Origin"_), you had to be corrected and you still persist. uBO and I have nothing to do with ABP, AdBlock or 2015-forked uBlock, and whoever made millions has nothing to do with me or uBO -- you keep trying to associate uBO with those completely unrelated projects. I will leave it at that, everybody can read and see it for themselves.

> doesn't like seeing its alternatives

We ask on our support thread to disable all other extensions to help narrow down issues for investigation purpose, so certainly having randos who never ever contributed anything to uBO giving advice to install more extensions on _our own_ support thread is going against what we are tying to do and is just adding burden to the process of investigation. People are free to install whatever they want, but not free to work against us on _our own_ support threads.

**Comment by 0x48piraj** [comment]
>  I have nothing to do with ABP, AdBlock or 2015-forked uBlock

Didn't you transfer the project?

> The uBlock project official repository was transferred to Chris Aljoudi[[16]](https://en.wikipedia.org/wiki/UBlock_Origin#cite_note-16) by original developer Raymond Hill in April 2015

How are they unrelated?

**Comment by 0x48piraj** [comment]
It's okay if you don't want to talk about it and I am completely in the wrong for assuming things from afar but I don't think I am in the wrong to relate these projects because they kind of are.

As you seem a bit defensive about it, I won't pester you and can understand what the "2015-forked uBlock" decided to do was not what you wanted.

People including me admire your principled stand against being paid for your work and providing such a tool with no strings attached while keeping it maintained for all these years. But if someone sells a fork of **your** software, it makes sense you get to be a part of the acquisition **especially if you were the one to transfer the ownership**. That's all I assumed. Nothing else.

**Comment by PNoveOfficial** [comment]
@0x48piraj English is not my native language, or even my secondary language. I can edit how many times I need

It may have been a personal attack indeed, I don't care. I think you are a jerk for trying to milk money out of people

> if you had more than two brain cells

You are not a saint either, and that was not directed only for me, but your end user (then you ask them money, in an annoying way). Nah, i'm out of this, dude. Like I said, thank you for "fixing" (I think it was intentional, but fine, "fix"....), at least I am not receiving that popup anymore.

**Comment by zolexander** [comment]
> > I saw in the antiadblock script what youtube does at the moment. Every 100 ms rewrites classes for example: this caused the glitches in the 2.5 version. Currently on youtube there is many setTimeout function and more MutationObserver for detect Adblockers.

This script causes even the new issue to delay firefox video player this is from the 
[Youtube antiadblock script](https://www.youtube.com/s/desktop/96766c85/jsbin/desktop_polymer_enable_wil_icons.vflset/desktop_polymer_enable_wil_icons.js)

```
function smb() {
      var a, b, c, d, e, h, l;
      return t(function (m) {
         a = new aj;
         b = document.createElement("ytd-player");
         try {
            document.body.prepend(b)
         } catch (p) {
            return m.return(4)
         }
         c = function () {
            b.parentElement && b.parentElement.removeChild(b)
         };
         0 < b.getElementsByTagName("div").length ? d = b.getElementsByTagName("div")[0] : (d = document.createElement("div"), b.appendChild(d));
         e = document.createElement("div");
         d.appendChild(e);
         h = document.createElement("video");
         l = new Blob([new Uint8Array([26, 69, 223, 163, 159, 66, 134, 129, 1, 66, 247, 129, 1, 66, 242, 129, 4, 66, 243, 129, 8, 66, 130, 132, 119, 101, 98, 109, 66, 135, 129, 4, 66, 133, 129, 2, 24, 83, 128, 103, 1, 255, 255, 255, 255, 255, 255, 255, 21, 73, 169, 102, 153, 42, 215, 177, 131, 15, 66, 64, 77, 128, 134, 67, 104, 114, 111, 109, 101, 87, 65, 134, 67, 104, 114, 111,
            109, 101, 22, 84, 174, 107, 169, 174, 167, 215, 129, 1, 115, 197, 135, 207, 96, 156, 234, 24, 157, 175, 131, 129, 1, 85, 238, 129, 1, 134, 133, 86, 95, 86, 80, 56, 224, 138, 176, 129, 1, 186, 129, 1, 83, 192, 129, 1, 31, 67, 182, 117, 1, 255, 255, 255, 255, 255, 255, 255, 231, 129, 0, 160, 204, 161, 162, 129, 0, 0, 0, 16, 2, 0, 157, 1, 42, 1, 0, 1, 0, 11, 199, 8, 133, 133, 136, 153, 132, 136, 63, 130, 0, 12, 13, 96, 0, 254, 229, 106, 0, 117, 161, 165, 166, 163, 238, 129, 1, 165, 158, 16, 2, 0, 157, 1, 42, 1, 0, 1, 0, 11, 199, 8, 133, 133, 136, 153, 132, 136, 63, 130, 0, 12, 13, 96, 0, 254, 232, 120, 0, 160, 187, 161, 152, 129, 3, 233, 0, 177,
            1, 0, 47, 17, 252, 0, 24, 0, 48, 63, 244, 12, 0, 0, 0, 254, 229, 106, 0, 117, 161, 155, 166, 153, 238, 129, 1, 165, 148, 177, 1, 0, 47, 17, 252, 0, 24, 0, 48, 63, 244, 12, 0, 0, 0, 254, 232, 120, 0, 251, 129, 0, 160, 188, 161, 152, 129, 7, 208, 0, 177, 1, 0, 47, 17, 252, 0, 24, 0, 48, 63, 244, 12, 0, 0, 0, 254, 229, 106, 0, 117, 161, 155, 166, 153, 238, 129, 1, 165, 148, 177, 1, 0, 47, 17, 252, 0, 24, 0, 48, 63, 244, 12, 0, 0, 0, 254, 232, 120, 0, 251, 130, 3, 233
         ])], {
            type: "video/webm"
         });
         h.src = lc(Mia(l));
         h.ontimeupdate = function () {
            c();
            a.resolve(0)
         };
         e.appendChild(h);
         h.classList.add("html5-main-video");
         setTimeout(function () {
            e.classList.add("ad-interrupting")
         }, 200);
         setTimeout(function () {
            c();
            a.resolve(1)
         }, 5E3);
         return m.return(a.promise)
      })
   }
```
I've tried modifying the 2.5 version: what happens if I remove the `ad-interrupting` class, after the ad is escaped.  Everytime somehow the  `ad-interrupting` class  suddenly was there, so I downloaded the latest youtube anti-adblock script (for my region), and after deobfuscation, I saw what caused the problem. The script is understandable. It's even delays the video player with 5 second. @0x48piraj write this extension. He can't download everywhere regional anti-adblock script, and alon can't studied everything. Youtube has much more resources and they can experiment with regions which works the best.
