### ISSUE TITLE
Skipped Video, Caused skip to fail. 

### ISSUE THREAD

**Issue by ItsTepsu** [0x48piraj/fadblock#129]
It's me again!

Noticing a lot of people saying that the ad blocker has been skipping videos, so I'll just say. Yeah they're right. But this also as a side effect of occasionally. So far this has only happened to me once. 

Things to note:
- 2 Advertisements, 1 unskippable, 1 skipable (in this order)
- Skipped whole video, and skimmed the ad at the end of the video
- Did not skip the final ad properly. Left with "visit site button" and "skip ad" 

If you choose to respond to this please explain in as much detail to help @0x48piraj understand what is happening. :)

**Comment by zolexander** [comment]
I think that's can be more helpful for @0x48piraj : 
`<div class="ad-interrupting">
<video src="blob:https://www.youtube.com/ddfb8790-03ce-4048-8a75-024144431be5" class="html5-main-video</video>
</div>`
That's the reason, why the extension skips the whole video. Youtube made a script what detects, when a Ad to fast skipped, and after specific against this extension will packed in a "ad-interrupting" class, what this extension uses to skip the whole video.
 I modifed a little bit the source and with console.log(document.querySelector(#container).innerHTML) got this information. Afterwards,when  the whole video skipped returns every class to the normal behaviour.

**Comment by 0x48piraj** [comment]
Guys, here's the original thread (https://github.com/0x48piraj/fadblock/issues/125), let's stick to one thread rather than opening multiple threads with the same issue.

@zolexander, I see, I will look into that, the problem is Google doesn't do patches globally so I am not seeing this happen at all. I will release a patch quickly nonetheless.

**Comment by 0x48piraj** [comment]
The new version has been submitted to the web store. Now we wait for the release. Other than the fix, an "update to latest" button was also added for fetching the latest patches from the in-built backend.

![image](https://github.com/0x48piraj/fadblock/assets/5800726/67d91d78-82d5-4d32-bd3f-730fe11aeaee)
