### ISSUE TITLE
While you wait for the new Fadblock version. This is to tide you over.

### ISSUE THREAD

**Issue by harkai84** [0x48piraj/fadblock#131]
While you wait for the new FadBlock update, I can recommend uBlock Origin to tide you over.
Make sure you clear the cache and update the filters.
When Fadblock is available again, simply disable uBlock Origin in Extensions.
If you short use uBlock Origin youtube may detect you. So be sure to stick with Fadblock.

**Comment by 0x48piraj** [comment]
Yes, thank you @harkai84. Just make sure you know what you're doing, uBO is a great alternative that also blocks ads on the whole Internet and not just YouTube, just beware if you're using it on YouTube as Google is hell-bent on fighting with traditional adblockers and there have been cases of account banning after getting detected.

**Comment by harkai84** [comment]
Yes, that's right. I only use it as an emergency when Fadblock has a bug.

**Comment by ochompsky** [comment]
unfortunately the developers of ubo are petulant manchildren who ban people from their subs just for posting alternatives.

**Comment by GentlePuppet** [comment]
If you use tampermonkey or greasemonkey you can use a small simple userscript I put together, initially based off of this but then tweaked over time cause this method stopped working, that does the same thing.
[Userscript](https://github.com/GentlePuppet/Gentles_Tampermonkey_Userscripts/raw/main/Youtube%20Better%20CSS%20Tweaks/Friendly%20Ad%20Block.user.js)

**Comment by fredngo** [comment]
> If you use tampermonkey or greasemonkey you can use a small simple userscript I put together, initially based off of this but then tweaked over time cause this method stopped working, that does the same thing. [Ad Skip Userscript](https://github.com/GentlePuppet/Gentles_Tampermonkey_Userscripts/raw/main/Youtube%20Better%20CSS%20Tweaks/Friendly%20Ad%20Block.user.js)

Does it work with Safari?

**Comment by 0x48piraj** [comment]
I will try to put out a version for Safari as as of now, FadBlock seems stable.
