### ISSUE TITLE
ABout the experience

### ISSUE THREAD

**Issue by Nghia323223** [0x48piraj/fadblock#132]
Something is wrong, as opposed to ffing the ads, it ended the video.
![Uploading Ảnh chụp màn hình 2023-11-18 203658.png…]()

**Comment by HollyBlocky** [comment]
Yes. On some videos, it'll end the video, and if you try to rewind it, audio will not play. If you refresh and restart your browser, it'll still only happen to that video and certain other ones.

**Comment by Nghia323223** [comment]
So videos longer than 10 mins are affected?

**Comment by raymond-1227** [comment]
> Yes. On some videos, it'll end the video, and if you try to rewind it, audio will not play. If you refresh and restart your browser, it'll still only happen to that video and certain other ones.

If sound doesn't play, just try to adjust the video volume with your up/down key, that's what helped me solving the problem where the sound is gone.

**Comment by Jacksonant** [comment]
@0x48piraj  is it due to ur extension new update or youtube new way of countering ur extension?

**Comment by 0x48piraj** [comment]
YouTube released a new patch, the whole discussion is here: https://github.com/0x48piraj/fadblock/issues/125.

In short, a new update is already been submitted and can come online any time now. Just hang on for a bit.

**Comment by 0x48piraj** [comment]
The new version is out, see if it solves the problem or not.

**Comment by Nghia323223** [comment]
![Uploading IMG20231121175620[1].jpg…]()
Not available on chrome store.

**Comment by 0x48piraj** [comment]
I am sorry but I can't see the image.
