### ISSUE TITLE
Strange glitch when reloading a youtube video in Desktop Firefox

### ISSUE THREAD

**Issue by eliezercazares** [0x48piraj/fadblock#133]
When you refresh, sometimes the video glitches, stops, then the page reloads itself.

Sharing video:
https://gemoo.com/tools/upload-video/share/584528035326840832?codeId=P5GGge1269ZBo&card=584528032508284928

**Comment by 0x48piraj** [comment]
Yeah, that's a known issue. Look into: https://github.com/0x48piraj/fadblock/issues/125

A new version will fix this issue. I'm sorry for the inconvenience.
