### ISSUE TITLE
Chrome: Youtube video still triggering adblocker alert on next video

### ISSUE THREAD

**Issue by sonyablu** [0x48piraj/fadblock#135]
Browser: Chrome, Version 119.0.6045.160 (Official Build) (64-bit)
Issue: The extension works for the first video played following reload of page, but when youtube serves another video on completion the Adblocker present alert displays for this new video.

**Comment by 0x48piraj** [comment]
That's not possible, go to `chrome://extensions` if you're using Chrome and post the screenshot.

**Comment by sonyablu** [comment]
Yeah, looks like something was not happy my end. I had removed my old adblocker before adding this extension, but it looks like it was still floating around causing issues. I've just restarted everything and done a fresh install of this extension, and it's working now. I'll close this as 'User error'.
