### ISSUE TITLE
skipping the video

### ISSUE THREAD

**Issue by DictionaryManHK** [0x48piraj/fadblock#136]
when I click on a video, it will automatically jump like an ad as the video showed. 

https://github.com/0x48piraj/fadblock/assets/85400057/8e61dd63-7b67-4466-b648-fef5a08a7d34

**Comment by hmes98318** [comment]
Chrome `version 119.0.6045.160 (x64)` also has the same issue

**Comment by WorldOfWheat** [comment]
6.4.3160.44 (Stable channel) stable (64-bit) 
has same problem

**Comment by Nghia323223** [comment]
Firefox same problem

**Comment by 0x48piraj** [comment]
The new version is out, see if it solves the problem or not.

**Comment by hmes98318** [comment]
v2.6 solved

**Comment by 0x48piraj** [comment]
Thank you for reporting in. This goes without saying but if you want any help or have any concerns, feel free to reach out again!


Closing.

**Comment by Randyp1234** [comment]
I just reinstalled and it still will not play mixes. After the first video it just skips the others one at a time.
