### ISSUE TITLE
The issue had not been fixed, still skipping the whole video, glitched and turned off the sound

### ISSUE THREAD

**Issue by Jts211** [0x48piraj/fadblock#137]

**Comment by WorldOfWheat** [comment]
same

**Comment by Randyp1234** [comment]
Same here - it seems to do it when opening in a new tab or if the video loading in one that automatically plays at the end of a previous one.

**Comment by Nghia323223** [comment]
Same

**Comment by 0x48piraj** [comment]
The new version is delayed. Hang in there guys. The version is in the review process. Wait for v2.6.

**Comment by 0x48piraj** [comment]
Now it sould be fixed. Check out v.2.6.

**Comment by Nghia323223** [comment]
Where? I haven't managed to get it on web store yet.

**Comment by 0x48piraj** [comment]
It's out on both Chrome and Firefox stores, just uninstall and reinstall if it's still not updated automatically.

Be sure to log in again if you have the license.
