### ISSUE TITLE
Its detected

### ISSUE THREAD

**Issue by mj55244** [0x48piraj/fadblock#138]
still playing add just a black screen for 6 seconds

**Comment by 0x48piraj** [comment]
Post a screenshot of your list of extensions.

**Comment by Alfonso-Jim** [comment]
It's detected 
![image](https://github.com/0x48piraj/fadblock/assets/32602264/9a214c0f-2fe3-402f-b3df-4460d21abb31)
![image](https://github.com/0x48piraj/fadblock/assets/32602264/31ffdb40-30a8-4f3b-b22c-9adc042ec8a7)

**Comment by 0x48piraj** [comment]
Update to the latest version (v2.6) and check again.

**Comment by 0x48piraj** [comment]
Glad it worked. This goes without saying but if you want any help or have any concerns, feel free to reach out again!

Closing.
