### ISSUE TITLE
Fixed version and optimized

### ISSUE THREAD

**Issue by themaoci** [0x48piraj/fadblock#139]
You can take whatever you want from it, i removed safari and tested it on operagx

the main part that changed is ```isAd || skipLock``` cause skipLock seems to not work

https://github.com/themaoci/FckYtAds

**Comment by themaoci** [comment]
to install get whole repository then extract it and load corespondong folder into the browser as external addon

**Comment by zolexander** [comment]
You can fix it, if you check  fad_videoPlayer readyState is ready to play. 
for example: 
` if(fad_videoPlayer.readyState !== 4) return;
` after you check if this fad_videoPlayer exists or not, or both:
`if(!fad_videoPlayer || fad__videoPlayer.readyState !== 4) return;`

**Comment by themaoci** [comment]
@zolexander thats why i told to use whatever you want - its my aproach but i was inspiring it on this code so all right goes to the creator of this repo.
