### ISSUE TITLE
Option to disable under given URL

### ISSUE THREAD

**Issue by Deckard9999** [0x48piraj/fadblock#142]
I noticed that extension tend to skip not only YT ads. I have some sort of random problem when I go to Pinterest. Something to disable the extension for a given URL should be nice.

Tnx for your work.

a.

**Comment by 0x48piraj** [comment]
I am sorry but FadBlock doesn't access any other URLs other than YouTube.com and it's subdomains (for blocking ads on YouTube Music).

I am sure some other extension is causing the problem.

**Comment by Deckard9999** [comment]
> I am sorry but FadBlock doesn't access any other URLs other than YouTube.com and it's subdomains (for blocking ads on YouTube Music).
> 
> I am sure some other extension is causing the problem.

Well, I suspected something like that. I will delete this useless conversation :-D tnx

a.
