### ISSUE TITLE
not working on chromium 87.0.4280.66 ?

### ISSUE THREAD

**Issue by RickzDO** [0x48piraj/fadblock#144]
Regards,

is this plugin languague dependant ?
installed package manuallly using Developer mode..

this is not working for spanish languague where Skid ad.... means **Saltar**
![image](https://github.com/0x48piraj/fadblock/assets/93270734/b40d87c9-4684-475f-ade2-859f9d2ad709)

please check... i will test disabling Ublock origin but i believe has nothing to do with it...
after installed i get some errors, maybe that's why not working?
check:
![image](https://github.com/0x48piraj/fadblock/assets/93270734/cf8fb744-2b4c-42db-b3c6-17e01129a033)

My Best Regards

**Comment by 0x48piraj** [comment]
Use the Chrome store:https://chrome.google.com/webstore/detail/fadblock-friendly-adblock/mdadjjfmjhfcibgfhfjbaiiljpllkbfc

**Comment by RickzDO** [comment]
> Use the Chrome store: https://chrome.google.com/webstore/detail/fadblock-friendly-adblock/mdadjjfmjhfcibgfhfjbaiiljpllkbfc
> 
> Read the announcement for more details. Closing.

![image](https://github.com/0x48piraj/fadblock/assets/93270734/ffdf8bd0-04d7-4071-9862-030a7915dc33)
