### ISSUE TITLE
WIll not play mixes....

### ISSUE THREAD

**Issue by Randyp1234** [0x48piraj/fadblock#147]
When playing mixes the first video plays then the others are skipped one at a time. EDIT - must've been a glitch because after closing and reopening Chrome, it seems fine. Sorry, I'd delete if I knew how.

**Comment by Randyp1234** [comment]
must've been a glitch because after closing and reopening Chrome, it seems fine. Sorry,

**Comment by Randyp1234** [comment]
It Is still doing this but sometimes only after several successful videos play.

**Comment by 0x48piraj** [comment]
I don't think it's an underlying issue of FadBlock as I use it daily and constantly use "song mixes" while working but I will investigate further.
