### ISSUE TITLE
Extension vanished from the Opera Addons page

### ISSUE THREAD

**Issue by jpluimers** [0x48piraj/fadblock#15]
https://addons.opera.com/en-gb/extensions/details/fadblock/ currently gives a 404, see https://archive.ph/2023.10.21-121825/https://addons.opera.com/en-gb/extensions/details/fadblock/

Not sure if there is anything within your power to have it reinstated though.

BTW: Great work. On Chrome it works even without adding an exemption in uBlock.

**Comment by 0x48piraj** [comment]
![image](https://github.com/0x48piraj/fadblock/assets/5800726/71387962-729f-4700-8858-33660573e399)
The Opera's team is not responding and is generally very slow to publish. I added the static link in case it gets published but it hasn't still.
