### ISSUE TITLE
Is there a version of this extension for Safari on MacOS?

### ISSUE THREAD

**Issue by doubleplusplus** [0x48piraj/fadblock#151]
Does this work for Mac Safari?

**Comment by STtraveller** [comment]
https://github.com/0x48piraj/fadblock#install-over-safari-on-macos

read the readme

**Comment by 0x48piraj** [comment]
Thanks for helping @STtraveller but the issue is valid. The old script does not work as of now and the Safari port is delayed.

Reference: https://github.com/0x48piraj/fadblock/issues/118
