### ISSUE TITLE
youtube updated there element class name

### ISSUE THREAD

**Issue by imoonkin** [0x48piraj/fadblock#152]
### issue:
ad auto skip not working

### reason:
this `skiplock` is `undefined` now. https://github.com/0x48piraj/fadblock/blob/3ef3ec7ac972a39dbc2b7639aad75829be6fb633/src/chrome/js/content.js#L7C15-L7C15

### fix:
```js
const skipLock = document.querySelector(".ytp-ad-preview-text")?.innerText || document.querySelector(".ytp-ad-preview-text-modern")?.innerText;
```

**Comment by 0x48piraj** [comment]
This repository is pretty outdated, read the announcement for more information.

Use: [Chrome web store](https://chrome.google.com/webstore/detail/fadblock/mdadjjfmjhfcibgfhfjbaiiljpllkbfc) or [Firefox Addons](https://addons.mozilla.org/addon/fadblock/)
