### ISSUE TITLE
recent update edge

### ISSUE THREAD

**Issue by Geofftechy** [0x48piraj/fadblock#158]
I have removed the fadblock extention after hearing bad things about it, I downloaded and intalled your new version, I use Edge browser which was recently updated (2 days ago) the uninstalled fadblock and your new one don't completely work atm, it intercepts the ad but requires me to manually click the skip button (there is no countdown), I am not sure if edge update caused this or something YT has done, just a heads up

**Comment by 0x48piraj** [comment]
Thanks for notifying, I will look into it.

**Comment by DigitalBear70** [comment]
As of February 5th / 2024, Edge has removed the Chrome Web Store version from Edge and from the Store itself (stating that it contains malware).  I grabbed this one.  Thank you for continuing to provide this.  I can confirm that it doesn't work 100% on Edge as of right now.  I still see ads at the beginning of videos.  The banner ads on the main page are gone so I'm confident that I have it installed correctly.  

Thanks again.  :)
