### ISSUE TITLE
Random refresh of all YouTube pages & 100% CPU load

### ISSUE THREAD

**Issue by jackloomen** [0x48piraj/fadblock#16]
All YouTube videos suddenly refreshed (progress/state lost) and CPU went to 100% for some time as a result.
I presume this was due to the extension updating. It happened once when the extension was installed and today was the second time it happened.

This is undesirable behavior.

**Comment by 0x48piraj** [comment]
The refreshing of videos only happen when the extension is installed, or updated. The page needs to be refreshed in order to properly block the ads, but people usually weren't doing that and hence the auto-refresh function.

I'll investigate the 100% CPU usage issue; that's a concerning sign.

**Comment by jackloomen** [comment]
The 100% cpu usage may have been due to multiple videos suddenly reinitializing and playing.
Could you include an option to disable the auto refresh on update? I do not want my videos randomly refreshing and losing their progress.

**Comment by 0x48piraj** [comment]
Got it, will do!

**Comment by 0x48piraj** [comment]
Addressed in https://github.com/0x48piraj/fadblock/commit/acb920a8040c1ce2a00c9c147b8307ee19bc6c65.
