### ISSUE TITLE
Not working on Chrome after all debugging steps

### ISSUE THREAD

**Issue by ORANGE-OASIS** [0x48piraj/fadblock#160]
The way I installed the extension was by downloading the files from GitHub, unzipping (extracting) the files, going to the extensions page, clicking "Load unpacked," selecting the folder for Chrome within the FadBlock files, then it showed it was installed as an extension.

I was still seeing ads, so I went through all the debugging steps. I don't have whatever "FadBlock Origin" is (unless it's the same thing just with two names); Here's what I did in order:

1. Disabled extensions on the detection list regardless of detection status (Return YouTube Dislike, Enhancer For YouTube)
2. Disabled other adblockers (only one: AdBlocker Stands) fully, since I already whitelisted YouTube on my adblocker before I installed the extension
3. Disabled all extensions except FadBlock, including ones that have do not affect YouTube: FadBlock was the only active extension
4. Closed out of every Chrome tab (and every other tab open) and reopened YouTube
5. Restarted my computer

Any help is appreciated!

**Comment by 0x48piraj** [comment]
Here's the link for FadBlock Origin: https://chromewebstore.google.com/detail/fadblock-origin-friendly/lmnhcklabcehiohmmeihcheoegomkghm?hl=en

As of now, the source is a bit outdated and it will be updated in a week or so. Thank you for your patience.
