### ISSUE TITLE
[Question] So is this repo is FadBlock Origin Version?

### ISSUE THREAD

**Issue by leoli0605** [0x48piraj/fadblock#163]
So is this repo is FadBlock Origin Version? Can I stop worrying about **security** issues if I install the release from this repository?

**Comment by 0x48piraj** [comment]
Yes. The malicious extension has been removed as of this moment. I have been going back and forth with the Google Dev team for days.

I will be updating the repository with the clean code as well as update the source to 2.7 and locking in the extension so it never gets traded ever again - if you're worried.

**Comment by leoli0605** [comment]
> Yes. The malicious extension has been removed as of this moment. I have been going back and forth with the Google Dev team for days.
> 
> I will be updating the repository with the clean code as well as update the source to 2.7 and locking in the extension so it never gets traded ever again - if you're worried.

Thanks your amazing work.

**Comment by 0x48piraj** [comment]
Sorry for the delay, probably will be updated by the next week. It's been a busy couple of days.
