### ISSUE TITLE
FadBlock Origin (clean & safe) ≠ FadBlock (now defunct & removed)

### ISSUE THREAD

**Issue by AlecDiramerian** [0x48piraj/fadblock#164]
<img width="859" alt="a" src="https://github.com/0x48piraj/fadblock/assets/111604851/99ea3d28-dd7b-402f-b218-b944565d8846">

**Comment by fabriziocarloni** [comment]
The original extension had changed hands and was then modified with malicious code to hack Facebook accounts. You can find everything here https://github.com/0x48piraj/fadblock/issues/157

**Comment by GeneralWadaling** [comment]
Happened to me as well
Watching vid and then chrome notify me 'bout it's blocked because it has malware

**Comment by 0x48piraj** [comment]
@AlecDiramerian, the extension has been removed as of this moment. I have been going back and forth with the Google Dev team for days.

I will be updating the repository with the clean code as well as update the source to 2.7 and locking in the extension so it never gets traded ever again - if you're worried.

**Comment by linuxtopia** [comment]
cant understand how others can inject malware your extension on chrome store?

**Comment by Rynn21** [comment]
Uninstall if you have the extension. Do NOT install any version of Fadblock in the future. Avoid Fadblock entirely.

**Comment by linuxtopia** [comment]
from this repo too?

**Comment by 0x48piraj** [comment]
Lol, no @linuxtopia, don't, see the code - it's clean - most of these comments are from different devs who picked up the code from this repository and just don't want people to use FadBlock.

Always see for yourself before believing anyone off the Internet. Lots of weirdos.

Read the announcement, read the issue https://github.com/0x48piraj/fadblock/issues/157. See everything for yourself.
