### ISSUE TITLE
malware?

### ISSUE THREAD

**Issue by Fandyfr** [0x48piraj/fadblock#166]
![image](https://github.com/0x48piraj/fadblock/assets/135007919/b6d950e9-e4ed-4e5c-9cdc-f23e609586ab)

**Comment by josemrs** [comment]
Probably the way of Google to take it out of the game.

**Comment by Deprot80** [comment]
Damn, there is no way to enable it back somehow? It was the only working adblocker for youtube for me. Can someone recommend any alternative?

**Comment by Fandyfr** [comment]
![image](https://github.com/0x48piraj/fadblock/assets/135007919/c334e264-38bf-4bcc-b7b0-90821e604a46)
I used the JS script and put it in ViolentMonkey and it worked again
