### ISSUE TITLE
Since a few days ago, fadblock doesn't block ads anymore (I'm on Firefox)

### ISSUE THREAD

**Issue by Genryuu111** [0x48piraj/fadblock#167]
Not that it counts but I paid for the extension.
Very simply, it stopped working a few days ago.
I'm on Firefox, Windows 10.

**Comment by iam-py-test** [comment]
The original author of this extension sold it, and the new owners turned it into malware: https://github.com/0x48piraj/fadblock/issues/157
I would **strongly** recommend you uninstall it, change all of your passwords, and invalidate all login sessions for your accounts.
Thank you

**Comment by Genryuu111** [comment]
Well shit.
Thank you very much!

**Comment by MGuerrera** [comment]
@iam-py-test have you by any chance examined the code of the corrupted extension?
Doesn't it just involve Facebook and Instagram sessions?

**Comment by iam-py-test** [comment]
I have not (yet). I _think_ people who did said it only involved Meta platforms, but there is no harm in changing the passwords to other platforms just in case.
Thanks

**Comment by visyan** [comment]
> Not that it counts but I paid for the extension. Very simply, it stopped working a few days ago. I'm on Firefox, Windows 10.

There is a new version of the extension, call FadBlock origin, published by the original owner (should be clean of malware)
But it doesn't skip the ads anymore... I'm on chrome. 
Google probably changed some things, breaking the script..

**Comment by 0x48piraj** [comment]
Thanks @visyan. The version is clean and as it has been always, I will see the changes when it gets deployed globally or I get some reports so I can fix it.

**Comment by 0x48piraj** [comment]
Also, the Firefox version was never sold - so it was safe from the jump and is. So don't worry about that. You can see it for yourself.

**Comment by Rynn21** [comment]
> Not that it counts but I paid for the extension. Very simply, it stopped working a few days ago. I'm on Firefox, Windows 10.

Delete anything to do with Fadblock. It's not a trustworthy extension.

**Comment by Rynn21** [comment]
> @iam-py-test have you by any chance examined the code of the corrupted extension? Doesn't it just involve Facebook and Instagram sessions?

It's a good idea anyways to change your passwords periodically. It's probably just Meta, but I'd rather play it safe.

**Comment by 0x48piraj** [comment]
Sure, delete it and use other extensions most of which lifted this exact codebase lol. Anyway, it was my fault for giving away the extension to a third party without realizing that 99% of the extension-developing industry is greedy (and stupid).
