### ISSUE TITLE
fadblock Lazy bag

### ISSUE THREAD

**Issue by missing372** [0x48piraj/fadblock#168]
First of all, I would like to thank the author for developing fadblock for us to use, and the lazy package of reply to question #157  is as follows.
fadblock has an old version of the malware, and the author is currently launching a new version. Information below

""The old version name is""
Fadblock friendly adblock for youtube (currently removed from the shelves)
""The new version is""
FadBlock Origin: Friendly YouTube™ Adblock""

![螢幕擷取畫面 2024-02-13 184959](https://github.com/0x48piraj/fadblock/assets/78717622/db493454-70d6-405b-b667-e6e77a81ce2d)
https://chromewebstore.google.com/detail/fadblock-origin-friendly/lmnhcklabcehiohmmeihcheoegomkghm

Please also refrain from excessively posting indecent information.
If you are afraid that your password will be stolen, please log out of all Google accounts and connected social software, and change your password.

**Comment by 0x48piraj** [comment]
I got the old version deleted by reaching out to the Chrome team and working with them. It's also thanks to many of the contributors whom I emailed to report the extension to speed up the process.

As per the exposure, it was limited to HTTP insecure sites as the malicious code was a cookie stealer. One of the contributors also launched a DDoS attack on their servers once I found their server's IP so there's that too.
