### ISSUE TITLE
Youtube detected the ad-blocker

### ISSUE THREAD

**Issue by MrBalls3456** [0x48piraj/fadblock#170]
This is the first day that this has happened It has never been detected until today which caught me off guard

**Comment by 0x48piraj** [comment]
It's the case with many adblockers.

You can search Reddit and will find many cases where known adblockers are getting detected. Just search "<INSERT A ADBLOCKER NAME> e.g. uBlock getting detected Google Chrome YouTube".

If you can't find it, I will drop some links, real tiring to search for it every time and send examples.

**Comment by 0x48piraj** [comment]
Oh, you meant YouTube and not Chrome. It must be other adblockers. Just see your extensions or add-ons. You shouldn't stack adblockers as it gets difficult to know which one is getting detected.

**Comment by davidgro** [comment]
I can confirm this. YouTube seems to be detecting FadBlock on Firefox. I've been using it for months, and excluded YouTube from my other adblocking first thing when I switched to Firefox and installed FadBlock initially.

**Comment by 0x48piraj** [comment]
Can you attach a DOM when that happens? It's working fine for me, personally.

**Comment by davidgro** [comment]
Can you please point me to directions on how to do that? then I'll switch back to Firefox, enable FadBlock, and wait for it to happen again.
Thanks!

**Comment by 0x48piraj** [comment]
I just pushed an update. Here's how to get the latest update:

![image](https://github.com/0x48piraj/fadblock/assets/5800726/0ff837f1-7b1e-4da6-af6d-48b786e881e8)
