### ISSUE TITLE
Cannot skip the ads of youtube in google chrome

### ISSUE THREAD

**Issue by Pacific-Feng** [0x48piraj/fadblock#171]
Hi,

I recently installed the extension (https://chromewebstore.google.com/detail/fadblock-origin-friendly/lmnhcklabcehiohmmeihcheoegomkghm), however, it is not skipping the ads.

I am wondering that if there is anything that I have to do addtionally to make it work normally.

Best regards,

**Comment by Frammer** [comment]
Have you refreshed the tab YouTube is open in?

**Comment by Pacific-Feng** [comment]
Yes, I have closed the chrome several times, but it still not work. I also reinstall the extension, and also not working.

**Comment by MaximusHoudini** [comment]
I am having the same issue as well, ads are playing and not being skipped, the tab needs to be refreshed multiple times before it works.  I've updated Chrome, the extension and still the same.

**Comment by blurskye** [comment]
you likely didnt disable your default adblock, you need to do that, fadblock cant help it if your default adblock gets detected

**Comment by MaximusHoudini** [comment]
Nope, I don't have any other adblocker installed.

**Comment by sonertari** [comment]
Can you make the following change in background.js and try again (this works for me):
```
//const skipLock = document.querySelector(".ytp-ad-preview-text")?.innerText;
const skipLock = document.querySelector(".ytp-ad-preview-text-modern")?.innerText;
```
In other words, I think youtube has changed that class name. (This patch should be made generic, if it really works for you too).

**Comment by boulwabd** [comment]
> Can you make the following change in background.js and try again (this works for me):
> 
> ```
> //const skipLock = document.querySelector(".ytp-ad-preview-text")?.innerText;
> const skipLock = document.querySelector(".ytp-ad-preview-text-modern")?.innerText;
> ```
> 
> In other words, I think youtube has changed that class name. (This patch should be made generic, if it really works for you too).

This appears to have fixed mine after the recent chrome update

**Comment by 0x48piraj** [comment]
It works for me as of now.

Seems like a geo-rollout. Let me know if that's still the case.

The classes are pushed on a server so it should be solved instantly without updating the extension.
