### ISSUE TITLE
it's now completely stopped working for me 

### ISSUE THREAD

**Issue by Monodark86** [0x48piraj/fadblock#173]
it's been 8 hours from fresh reinstall of win 11 kind of feel a tad let down as I paid for this as well it might be time to update your code again for the app.

![Screenshot 2024-03-02 201435](https://github.com/0x48piraj/fadblock/assets/150067055/93f603b3-282b-4711-ab9c-55219770eac6)

**Comment by Archaicus** [comment]
It has not been working in over a week for me on any of my machines with Firefox.
![NoWork](https://github.com/0x48piraj/fadblock/assets/162496400/f40986dd-d212-43a9-ae6e-8c8bb15a13b7)

**Comment by Monodark86** [comment]
that's pretty bad if it's over a week for you Archaicus.

I'm still waiting for a response for this ticket 0x48piraj.

**Comment by 0x48piraj** [comment]
Is this still the case? It's working just fine for me so I haven't been looking into the issues.

If it's still the case, please capture a live DOM snapshot and attach it below so I can look at the source.

**Comment by Monodark86** [comment]
i did a clean reinstall again touch wood so far all is working ok 

but forgot to update on here

**Comment by 0x48piraj** [comment]
Hmm. Something's amiss. I will look into it when I get some time, hopefully this week.

**Comment by 0x48piraj** [comment]
The latest YouTube patch has not been deployed globally yet, so the previous version continues to function for the time being.

I've made updates to the backend, so if anyone encounters issues with the current version, they can simply update their installed FadBlock.

Here's how:

![image](https://github.com/0x48piraj/fadblock/assets/5800726/0ff837f1-7b1e-4da6-af6d-48b786e881e8)

**Comment by 0x48piraj** [comment]
The issue was resolved this morning. Closing.

Reference thread for leaving remarks regarding this issue: https://github.com/0x48piraj/fadblock/issues/182
