### ISSUE TITLE
completely stopped working on Opera GX

### ISSUE THREAD

**Issue by Drpushface** [0x48piraj/fadblock#174]
completely stopped working on Opera GX after many months of it working just fine. hope it gets fixed so I can continue to use this awesome extension

**Comment by 0x48piraj** [comment]
The latest YouTube patch has not been deployed globally yet, so the previous version continues to function for the time being.

I've made updates to the backend, so if anyone encounters issues with the current version, they can simply update their installed FadBlock.

Here's how:

![image](https://github.com/0x48piraj/fadblock/assets/5800726/0ff837f1-7b1e-4da6-af6d-48b786e881e8)

**Comment by 0x48piraj** [comment]
The issue was resolved this morning. Closing.

Reference thread for leaving remarks regarding this issue: https://github.com/0x48piraj/fadblock/issues/182
