### ISSUE TITLE
As of April 5, stopped working (for the most part)

### ISSUE THREAD

**Issue by Hufflepuffhatesyoutubeads** [0x48piraj/fadblock#177]
It was working perfectly fine google chrome browser yesterday, and now it isn't skipping the ad. Whenever it has two ads, I have to click skip to skip the first one, and the second one just doesn't even happen. hopefully, you can fix it soon. No rush, just wanted to bring to your attention and see if others were experiencing the same

**Comment by 0x48piraj** [comment]
The latest YouTube patch has not been deployed globally yet, so the previous version continues to function for the time being.

I've made updates to the backend, so if anyone encounters issues with the current version, they can simply update their installed FadBlock.

Here's how:

![image](https://github.com/0x48piraj/fadblock/assets/5800726/0ff837f1-7b1e-4da6-af6d-48b786e881e8)

**Comment by 0x48piraj** [comment]
The issue was resolved this morning. Closing.

Reference thread for leaving remarks regarding this issue: https://github.com/0x48piraj/fadblock/issues/182
