### ISSUE TITLE
Fadblock not working again

### ISSUE THREAD

**Issue by Zjefken** [0x48piraj/fadblock#183]
Since today ads aren't skipped anymore, I've already tried updating the extension in the extension menu itself and that isn't fixing the issue.

**Comment by Farseer123456789** [comment]
Yup same on Firefox

**Comment by MrDrDevil** [comment]
same here
---chorme

but 0x48piraj said in other issues he testing "new version" and will "drop  it before tomorrow's end."
"https://github.com/0x48piraj/fadblock/issues/182#issuecomment-2074607706"

**Comment by 0x48piraj** [comment]
Redirecting to the original thread #182
