### ISSUE TITLE
Fadblock not working on 4/24/24 - Chrome

### ISSUE THREAD

**Issue by liftacar** [0x48piraj/fadblock#184]
No longer skipping ads. This happened before and closing/reopening Chrome browser restored it but not this time.  Not skipping any ads.

**Comment by ursupermann222** [comment]
Same here. Earlier it was blocking the initial ad, but mid-roll ads would still get through. Now all ads play.

**Comment by jimsstone** [comment]
Not working on ChromeOS Version 123.0.6312.134 (Official Build) (64-bit)

**Comment by 0x48piraj** [comment]
Redirecting to the original thread #182
