### ISSUE TITLE
Doesn't work on my PC, Works on my laptop

### ISSUE THREAD

**Issue by FBomm** [0x48piraj/fadblock#185]
Hello,

I was using the fadblock extention for a while now, I have supported the extention. It was working the past couple of days after a few days of not working, assuming there was an update, thanks for that.

I went on my laptop after fadblock had been functional again and it worked perfectly on my laptop,then wehen I switched back to my PC, it hasn't worked since I went back on my PC.

Should it work between both devices?

**Comment by 0x48piraj** [comment]
Wait till v1.1 drops, the extension will auto-update. Here's the main thread: https://github.com/0x48piraj/fadblock/issues/182

Closing.
