### ISSUE TITLE
fadblock origin doesn't work anymore

### ISSUE THREAD

**Issue by Anietjuh** [0x48piraj/fadblock#188]
since a few days fadblock origin doesn't skip the ads anymore on youtube i have windows 10 and google chrome thought maybe u wanted to know ... Much love and thank u for the things you already did in the past regarding to fadblock origin <3

**Comment by 0x48piraj** [comment]
![image](https://github.com/0x48piraj/fadblock/assets/5800726/2fe18e92-0d11-4b29-aaba-3c53342593d6)

I pushed the update a week ago but Chrome has not yet updated the extension. Here's the detailed thread: https://github.com/0x48piraj/fadblock/issues/182

Closing.
