### ISSUE TITLE
I paid to support the creator last week and now it doesn't work anymore...

### ISSUE THREAD

**Issue by Franckyboyz** [0x48piraj/fadblock#189]

**Comment by 0x48piraj** [comment]
![image](https://github.com/0x48piraj/fadblock/assets/5800726/2fe18e92-0d11-4b29-aaba-3c53342593d6)

I pushed the update a week ago but Chrome has not yet updated the extension. Here's the detailed thread: https://github.com/0x48piraj/fadblock/issues/182

Closing.
