### ISSUE TITLE
FadBlock does not work anymore

### ISSUE THREAD

**Issue by edenseca** [0x48piraj/fadblock#19]
I have been using it for the past few days now. Just today, it has stopped working. I tried the newer version 1.3 but it no longer forwards through any ads.

**Comment by lianglee** [comment]
Seems chrome disable itself

**Comment by edenseca** [comment]
Ah so it is a chrome issue? Does it work on firefox?

**Comment by likueimo** [comment]
Using the browser Chrome or Firefox, the extension FadBlock works fine for me.

**Comment by GroggyOtter** [comment]
Can confirm it's not working as of 24Oct2023.

![](https://i.imgur.com/p3kh1ok.png)

Ensured both Chrome and the addon were up-to-date and reloaded both. Ads are still appearing and running the full course.

On a side note, the TamperMonkey script [RemoveAdBlockThing](https://github.com/TheRealJoelmatic/RemoveAdblockThing) seems to not only work fine but it's been improved. Those wanting an alternate solution until this addon gets fixed should check it out.

I keep both installed but only use 1 at a time.  
If one breaks, disable it and swap to the other.  
¯\\\_(ツ)\_/¯

That being said, big thx to `0x48piraj` for all the work you've put in so far. The amount of people who **are** thankful far outweighs the amount of visual thanks you've gotten. Believe me, there are TONS of people who love you for trying to help with this YT adblocker bullshit.  

Much respect.

**Comment by Rynn21** [comment]
It stopped working for me today (on Chrome). I have had the extension installed. 
I got the warning that playback would be blocked after 3 videos.

**Comment by samliu23** [comment]
stopped working on Edge

**Comment by 0x48piraj** [comment]
Seems to be working for many others as well as myself, which browser/platform are you guys using, and can y'all dump the current DOM state so I can examine closely?

#### How to?
> When FadBlock doesn't work on a specific ad, while the ad is showing, pause the ad, then using the Web Inspector (F12), go to the Elements tab, right click on the `<html>` tag in your code and select `Copy`->`Copy outerHTML`. Then paste that into a new file and save.

**Comment by CingYan** [comment]
Chrome 118.0.5993.90 (stable)
note: my default language is mandarin

[notwork.txt](https://github.com/0x48piraj/fadblock/files/13176535/notwork.txt)

**Comment by atanas-nikolov** [comment]
Yeah, it does not work for a couple of days and I have my other AdBlock add-ons disabled.

**Comment by Rynn21** [comment]
When it does work, on Chrome (Windows 10), ads attempt to play but skip. The days leading up to these issues, ads didn't even show up for a second.

**Comment by 0x48piraj** [comment]
Thank you @CingYan, I found the new patch Google implemented and am working on a new release which will work, in addition, it's going to successfully block out survey ads as well as homepage sponsored banners.

**Comment by 0x48piraj** [comment]
Addressed in https://github.com/0x48piraj/fadblock/commit/acb920a8040c1ce2a00c9c147b8307ee19bc6c65. Closing.

**Comment by h0n3ym4k** [comment]
chrome 119.0.6045.124 . fadblock does not work
