### ISSUE TITLE
The second ad that came right after wasn't detected

### ISSUE THREAD

**Issue by ChienKaiMa** [0x48piraj/fadblock#191]
I just installed this extension and found out it is working. However, the extension skipped the first ad but not the second that came right after. I was using YouTube Music with a playlist, FYI.  Later, I observed that some ads are not skipped, while the "Video Ads blocked since installation" counter was going up.  I guessed they all share the same reason.

**Comment by 0x48piraj** [comment]
Still the case?

**Comment by ChienKaiMa** [comment]
Strangely, I haven't noticed similar events later this week. I think I'll close this issue. Thank you very much!
