### ISSUE TITLE
YouTube detects FadBlock as an adblocker

### ISSUE THREAD

**Issue by JandJplusJ** [0x48piraj/fadblock#194]
If an ad plays before a video, YouTube detects it as an adblocker. Refreshing the page and hoping to not get an ad is a temporary solution. However, YouTube does not detect it if an ad plays mid video for whatever reason.

Keep up the good work! :)

**Comment by Grg76** [comment]
Same problem here.  I hope Piyus can fix it soon :)

**Comment by MauriceStrickland** [comment]
Seeing this as well

**Comment by Tired-Dancer** [comment]
Also having this problem on Opera

**Comment by 0x48piraj** [comment]
I also got the same thing today, I am looking into it - but I also have uBlock Origin installed (though disabled on YouTube for obvious reasons) and when I uninstalled uBO - I stopped getting the warnings.

Suggestion: Try to run FadBlock in an isolated environment (remove any other adblockers) and see if the warning goes away because for me, it did.

**Comment by Tired-Dancer** [comment]
Okay so now there's a new version of this I'm seeing- if it would show an ad, you see the 'no adblockers on youtube' message, but upon refreshing, regardless of if it would show an ad or not it plays. Not sure if this is Opera exclusive variant

**Comment by DigitalBear70** [comment]
I just had the same thing happen.  I refreshed the page and it seems to play now.  Just a heads up.  

Microsoft Edge
Version 125.0.2535.67 (Official build) (64-bit)

**Comment by SheeepsAreNice** [comment]
I started experiencing this on Brave yesterday (with shields down for YouTube). However, when going through extensions, I remembered that I installed uBlock Origin a long while ago but had never activated it. Removing uBlock Origin has seemingly solved the issue. I'm assuming that YouTube is now suddenly detecting and flagging the mere existence of the uBlock Origin extension, even if it's not activated or running.

**Comment by 0x48piraj** [comment]
Exactly @SheeepsAreNice. I came to the same conclusion as well.

Here's the fix: disable or uninstall popular adblock extensions (for now) until they release a patch.


I have said this numerous times, the beauty of FadBlock is that YouTube can never detect it's presence, they can break the app temporarily by rewriting internals of YouTube but they can't "detect" us. It works by abusing their own code, we don't block ads, we skip 'em. Cheers!

**Comment by ZMYaro** [comment]
I removed my regular adblocker extension (previously, I only disabled it on YouTube), and it still gives me this screen when I use FadBlock:
![image](https://github.com/0x48piraj/fadblock/assets/763405/3495ce46-980a-4966-ae4c-8478ff6e4ac3)

When I have Adblock Plus installed but disabled on YouTube, and I remove FadBlock, I don't get that message.

**Comment by patrickkdev** [comment]
They are probably detecting an ad blocker when a video starts playing immediately, even though there was supposed to be an ad of at least 5 seconds in duration.
