### ISSUE TITLE
It's getting detected

### ISSUE THREAD

**Issue by HackerDragon9999** [0x48piraj/fadblock#197]
Fadblock is now getting detected on Firefox. I use this program all the time to watch youtube (but am too poor to donate :(, sorry).

**Comment by HackerDragon9999** [comment]
Never mind, this is a duplicate.

**Comment by racerx2** [comment]
dont work in brave

**Comment by Farseer123456789** [comment]
Yup it's getting detected in Firefox.  Getting the ad blocker notifications.  Hope it can get solved

**Comment by DigitalBear70** [comment]
FadBlock was just detected by YouTube for me.  

I use Edge browser.

**Comment by Wilson076** [comment]
Bad news, FadBlock Origin has been detected by YouTube in Chrome, Version 126.0.6478.57 (Official Build) (64-bit).

It's happened at least 6 times and has also been detected even when deleting other Adblockers in YT. Although it can bee contiue by restart the yt, not sure that annoyed 3 times locked piceture from yt will restroed one day.

**Comment by harkus** [comment]
It's going to get worse: https://techcrunch.com/2024/06/16/youtube-is-testing-another-way-to-combat-ad-blockers

**Comment by 0x48piraj** [comment]
As said, the extension works and is daily used by me and most of my peers. The moment it really stops working, I fix it up.

To all those who are running other adblockers side by side, I cannot help, they are getting detected. Worse yet, YouTube puts a tracker when detected and that causes the "I deleted the other adblockers and I am still getting detected" queries.

Even after logging out, clearing out the cookies and logging back in sometimes doesn't fix the issue for some (it fixed for most of us) hinting they are marking the accounts using adblockers server-side but I can't say for sure as FadBlock works perfectly for me as of now and many of the supporters I have talked to over the email.

**Comment by 0x48piraj** [comment]
I am keeping an eye out but so far, it's genuinely working for my and everyone else and by recent reviews - it's being solidified.

To be perfectly candid, I have had some FF'ing of videos when I am watching a mix and I am working on that (no YouTube Adblocker banners though).

Everyone can move to a singular thread so it's easy to track and work through issues: https://github.com/0x48piraj/fadblock/issues/196
