### ISSUE TITLE
Not Working Extension on Chroma. 

### ISSUE THREAD

**Issue by Ranjeetdigimind** [0x48piraj/fadblock#198]

**Comment by 0x48piraj** [comment]
As said, the extension works and is daily used by me and most of my peers. The moment it really stops working, I fix it up.

To all those who are running other adblockers side by side, I cannot help, they are getting detected. Worse yet, YouTube puts a tracker when detected and that causes the "I deleted the other adblockers and I am still getting detected" queries.

Even after logging out, clearing out the cookies and logging back in sometimes doesn't fix the issue for some (it fixed for most of us) hinting they are marking the accounts using adblockers server-side but I can't say for sure as FadBlock works perfectly for me as of now and many of the supporters I have talked to over the email.
