### ISSUE TITLE
Getting detected, YouTube threaten me to block my YT player

### ISSUE THREAD

**Issue by CarniFish** [0x48piraj/fadblock#199]
![螢幕擷取畫面 2024-06-19 152951](https://github.com/0x48piraj/fadblock/assets/173241607/6e0392fb-fc69-42b1-910b-38dc20d881e8)
Just as stated, YouTube is constantly detecting this extension, and now is threaten to block my YT player after three videos. I have tried update, still don't solve.

**Comment by Zjefken** [comment]
I have the same issue, no other ad blocking extensions enabled. Really hope this can be fixed.

**Comment by ene0s** [comment]
here_we_go_again_meme.jpg

Every day I'm grateful for this plugin, probably the one of the most useful for my internet usage, regarding all the Youtube vids I watch on a daily basis. Sometimes I wonder what was the skipped add, but I'm not that curious.

**Comment by 0x48piraj** [comment]
Thanks @ene0s for those kind words.

As said, the extension works and is daily used by me and most of my peers. The moment it really stops working, I fix it up.

To all those who are running other adblockers side by side, I cannot help, they are getting detected. Worse yet, YouTube puts a tracker when detected and that causes the "I deleted the other adblockers and I am still getting detected" queries.

Even after logging out, clearing out the cookies and logging back in sometimes doesn't fix the issue for some (it fixed for most of us) hinting they are marking the accounts using adblockers server-side but I can't say for sure as FadBlock works perfectly for me as of now and many of the supporters I have talked to over the email.

**Comment by martinrokidomino** [comment]
it's also getting detected for me, i am on firefox, so the moment fadblock skips the ad, it gets detected.

**Comment by 0x48piraj** [comment]
I am keeping an eye out but so far, it's genuinely working for my and everyone else and by recent reviews - it's being solidified.

To be perfectly candid, I have had some FF'ing of videos when I am watching a mix and I am working on that (no YouTube Adblocker banners though).

**Comment by 0x48piraj** [comment]
Move here: https://github.com/0x48piraj/fadblock/issues/196
