### ISSUE TITLE
List of conflicting and non-conflicting extensions/plugins

### ISSUE THREAD

**Issue by cnekmp** [0x48piraj/fadblock#20]
I have several extensions (Firefox) for YouTube and I had issues with playing videos because of them conflicting with Fadblock. Is it possible to gather list so the users will know which plugins they should avoid?
For example:

Conflicting:
uBlock Origin (if youtube is not whitelisted)
Enhancer For Youtube

Non-conflicting:
no-more-rounded-corners
Return YouTube Dislike
SponsorBlock for YouTube

**Comment by 0x48piraj** [comment]
Sure, I'd create a list.
