### ISSUE TITLE
Malware?

### ISSUE THREAD

**Issue by rogacz1988** [0x48piraj/fadblock#200]
I am getting popup on every page who force me to pay, and that popup is slowing youtube loading....

**Comment by SheeepsAreNice** [comment]
No, not malware. The details of the extension make it clear that in-app purchases will support the developer

**Comment by ene0s** [comment]
It's weird that is it appearing every time, in my experience it appears once in a while, maybe every few days.

**Comment by SheeepsAreNice** [comment]
The OP is also using emotive language ('force') so I'd query whether the 'every page' claim is accurate tbh

**Comment by 0x48piraj** [comment]
Every adblocker is constantly hit by those warnings, you can quick google and find Reddit threads of uBO and the likes getting that warning.

To be perfectly candid and transparent, the former extension was handed over to a third-party and misused - which was swiftly deleted by the Chrome Dev team after getting reported by me and other supporters.

This extension is as clean as they come and, as promised after the incident, never would be handed over to anyone.

**Comment by rogacz1988** [comment]
> The OP is also using emotive language ('force') so I'd query whether the 'every page' claim is accurate tbh

You need to calibrate your dictionary ;)
Force means force. If I get a pop-up 3x when entering 3 videos then it is not a request, but a force. 
Plus considering how it slows down youtube loading it is no different from youtube policy ;)

**Comment by SheeepsAreNice** [comment]
> > The OP is also using emotive language ('force') so I'd query whether the 'every page' claim is accurate tbh
> 
> You need to calibrate your dictionary ;) Force means force. If I get a pop-up 3x when entering 3 videos then it is not a request, but a force. Plus considering how it slows down youtube loading it is no different from youtube policy ;)

Then support the developer, as I did, or use something else. Nobody is forcing you to use this extension and freeload off their hard work.

**Comment by rogacz1988** [comment]
Tia, I continue to have a free choice, and it is one thing to be forced and another to do it out of free will ;)

**Comment by SheeepsAreNice** [comment]
Good for you. Seems that the real issue here is not with the extension, though, so take any futher butthurt to reddit, please. This is not the place.

**Comment by rogacz1988** [comment]
Nope, extension have malware who is forcing to pay. If you don't understand you can don't answer anymore, you are just a fake account.

**Comment by ene0s** [comment]
have you tried uninstalling it and installing the extension back from the Chrome store ?

Its normal behavior should be to show the support the dev pop-up only once in a while, not at every video.

**Comment by 0x48piraj** [comment]
That's simply not true @rogacz1988. The videos come after every 100 or so ads and they definitely do not slow down YouTube at all in reality, I am already very busy combating YouTube's increasing strings of spaghetti code that make their own site slower.

The titling of "malware?" was 'malicious' to begin with. I do not think you are being forthcoming about your report.

Trolling is not condemned but unfortunately not tolerated, so, closing this one.

Have a nice day, or not!

**By the way, thanks a lot for having my back @SheeepsAreNice. You do not need to waste your precious time but I highly appreciate you for clearing the air.**
