### ISSUE TITLE
yt keeps detecting it 

### ISSUE THREAD

**Issue by mapelfocs** [0x48piraj/fadblock#205]
i havent had an actual adblock on operaGX for a while (yes even the built in one) since ive disabled it on yt but yet yt only detects me having an adblock ONLY when i have fadblock on please find a way to fix it bc it blocks the video player

**Comment by tassietigermaniac** [comment]
I second this. It appears that YouTube has started to detect this Adblock which is unfortunate

**Comment by tassietigermaniac** [comment]
![YTAdBlock](https://github.com/0x48piraj/fadblock/assets/23428898/35352dee-dade-4b9f-805e-f76800337c8a)

**Comment by DigitalBear70** [comment]
Unfortunately I also have to report that FadBlock is being detected as an Ad Blocker on YouTube.  

I have completely cleared my cache and uninstalled any other extensions that have any kind of Ad Block capability.  Not disabled them, I have removed them and cleared the cache.  

Here's hoping this can be fixed.  Thank you for your perseverance.

Microsoft Edge
Version 126.0.2592.87 (Official build) (64-bit)

**Comment by JTH366** [comment]
Fadblock has stopped working completely. I am using Chrome, I have no other extensions.

**Comment by huggiebao2** [comment]
Same problem. I once thought it was the whitelist function of other ad blockers failing, causing it to be detected by YouTube. And now I have one chance left.

**Comment by DigitalBear70** [comment]
Can confirm it's no longer working consistently.  I'm on the latest version of Edge.  I have no other ad blocking programs running and it was working fine a few days before. 

Hope you're able to get it working again, thank you for your perseverance.

**Comment by Sublimehurdle** [comment]
First time using the extension, it didn't work immediately. And now YT detects it and requested to remove it.

**Comment by 0x48piraj** [comment]
Read: https://github.com/0x48piraj/fadblock/issues/206

Closing as duplicate.
