### ISSUE TITLE
Proposed solution for recent blockage failure 

### ISSUE THREAD

**Issue by Cubiking** [0x48piraj/fadblock#207]
Disclaimer: I am not an experienced programmer. My suggestion may not be practical and my wording may be confusing. If I ve unfortunately wasted your time, please allow to deeply apologize.

I am using the free version available in chrome web store. Keep Reloading the youtube video page until the video can be played without ads seems to be a solution. I guess conditonal reloading is not difficult in JS. Not sure if detecting the video's playing status is difficult.

**Comment by 0x48piraj** [comment]
Any unstable network degrades the performance of FBO ever so slightly because of race conditions. I am always looking for a solution to make the software better but it's hard when YouTube keeps changing it's source adding unnecessary adblock detection junk that makes their own site work slower.
