### ISSUE TITLE
FadBlock not working on Google Chrome as of 7/9/24

### ISSUE THREAD

**Issue by liftacar** [0x48piraj/fadblock#208]
Purchased FadBlock and been using this for quite sometime.  As of yesterday it is no longer working on YouTube ads being run on Google Chrome.

I get the YT detected an adblocker pop-up.  All my other blockers are turned off on YouTube.  Then when I try to refresh the video starts over at the beginning of the video and not where I left off.  Also, sometimes, the video just stops altogether and it'll start playing a new video next (for instance when I'm watching something on my 'Watch Later' playlist).

Anyways, FadBlock has run into a roadblock.  Hoping Raj will push a fix for this.

**Comment by benalt613** [comment]
I've also had this issue. I do have uBlock Origin, but it has been deactivated for YouTube for many months so i do not think it is the issue. Also, when i deactivate FadBlock, everything appears fine. I am wondering if YouTube detects how long the ads run for and if it is too quick then it puts up the message?

**Comment by 0x48piraj** [comment]
Read: https://github.com/0x48piraj/fadblock/issues/206

Closing as duplicate.
