### ISSUE TITLE
Worked fine for a few days, now getting "Ad blockers violate YouTube's Terms of Service" message (Chrome)

### ISSUE THREAD

**Issue by menyme** [0x48piraj/fadblock#209]
I recently downloaded your program to my Chrome browser for the first time about a month or two ago.  I thought it worked great at first.  It sped through the ads very quickly.  Then it slowed down and I saw more seconds of the ad than before.  About a week ago,  YT detected it and when an ad comes up, I get the "Ad blockers violate YouTube's Terms of Service" message.  If I reload the page, I can continue watching the video until the next ad pops up and then the same thing happens.  So I am constantly getting this message and reloading to bypass it, but doing that sometimes brings me back to the beginning of the video and also takes me out of full screen mode.  I uninstalled it and then downloaded it again, and it worked fine for only a day until it was detected again.  So, if you can fix this so it is no longer detectable, that would be awesome.  Thanks!

**Comment by seebeedub** [comment]
Yes - same with me and I would recommend investigating FreeTube. Seems to be good video infrastructure without tracking or ads. Only one day but so far so good.

**Comment by 0x48piraj** [comment]
Read: https://github.com/0x48piraj/fadblock/issues/206

Closing as duplicate.
