### ISSUE TITLE
Youtube recognises it as adblock

### ISSUE THREAD

**Issue by percivaldotexe** [0x48piraj/fadblock#21]
I've disabled my original adblocker, but every time I click on a video, youtube is blocked with the typical "adblockers violate youtube's terms and service" page. I reloaded the browser, even completely restarted the browser, and still the same. Is there something else I need to do?? This is extremely frustrating

**Comment by 0x48piraj** [comment]
Which browser, platform are you using, and can you dump the current DOM state so I can examine closely?

#### How to?
> Using the Web Inspector (F12), go to the Elements tab, right click on the `<html>` tag in your code and select `Copy`->`Copy outerHTML`. Then paste that into a new file and save.

**Comment by Confused011** [comment]
Also getting the same issue, worked fine last night, this morning Youtube is detecting it.

**Comment by 0x48piraj** [comment]
Addressed an issue in which FadBlock was not working for some in https://github.com/0x48piraj/fadblock/commit/acb920a8040c1ce2a00c9c147b8307ee19bc6c65.

**Note:** YouTube can't detect FadBlock. It just can't as it doesn't do anything like an adblocker. If you're getting detected, read the FAQ carefully.
