### ISSUE TITLE
Sometimes not working, sometimes showing ads???

### ISSUE THREAD

**Issue by Tired-Dancer** [0x48piraj/fadblock#210]
Okay so I use Opera and recently I have been having the standard "ad blockers are not allowed on youtube" problem but recently I have also started having the ads just play as normal? It just started today

**Comment by er-koch** [comment]
I too am receiving the "Ad blockers violate YouTube's Terms of Service" error.

**Comment by WeebNetsu** [comment]
Same issue
<img width="724" alt="image" src="https://github.com/user-attachments/assets/abe9ebdf-0683-46e6-88f8-954e909f2217">

**Comment by WeebNetsu** [comment]
I wonder, since it's not blocking any ad scripts, if YouTube has put a timer on to check if ads play for at least 5 seconds? Especially since it only shows that message after ads have been skipped and not before

**Comment by 0x48piraj** [comment]
Read: https://github.com/0x48piraj/fadblock/issues/206

Closing as duplicate.
