### ISSUE TITLE
I have donated $5.99 but it still doesn't work

### ISSUE THREAD

**Issue by vividolphin** [0x48piraj/fadblock#213]
![PixPin_2024-07-20_13-49-35](https://github.com/user-attachments/assets/d68408ce-93ba-409f-aa44-8bdc368b2647)
![PixPin_2024-07-20_13-49-47](https://github.com/user-attachments/assets/6bbddb24-7602-46d0-b8ca-666d926caba1)

**Comment by 0x48piraj** [comment]
As said, the extension works and is daily used by me and most of my peers. The moment it really stops working, I fix it up.

To all those who are running other adblockers side by side, I cannot help, they are getting detected. Worse yet, YouTube puts a tracker when detected and that causes the "I deleted the other adblockers and I am still getting detected" queries.

Even after logging out, clearing out the cookies and logging back in sometimes doesn't fix the issue for some (it fixed for most of us) hinting they are marking the accounts using adblockers server-side but I can't say for sure as FadBlock works perfectly for me as of now and many of the supporters I have talked to over the email.

**Comment by 0x48piraj** [comment]
Move to https://github.com/0x48piraj/fadblock/issues/196

**Comment by 0x48piraj** [comment]
Also, read: https://github.com/0x48piraj/fadblock/issues/206

**Comment by vividolphin** [comment]
Thank you very much for the staff's timely reply. I cleared the cookies and browsing history within 7 days, logged out and logged back into my Google account, and it was back to ad-free status. It seems that this is feasible. You can try this method. Thanks to the author again.
