### ISSUE TITLE
No longer working no matter what I do or how much I update it - Youtube detects it and forces me to disable it.

### ISSUE THREAD

**Issue by KnightGabriel** [0x48piraj/fadblock#215]
I'm a bit disappointed because for a while this was working very well with almost no issues, but now Youtube has started detecting it since a couple weeks ago and I was forced to switch to ublock as that is the only other adblocker that works well for me atm. Is there any way to fix this?

**Comment by KnightGabriel** [comment]
@0x48piraj you there?

**Comment by Wilson076** [comment]
It is the same situation with my pc chrome, Frinedly Adblock can be detected by YouTube in its every operation and force me to disable it.

**Comment by Larkspeed** [comment]
Same here.

Windows 10 with Chrome

**Comment by Ggboy158** [comment]
i have gotten same issues
windows 10 chrome

**Comment by 0x48piraj** [comment]
Sorry for the late reply - yes there is. I have posted it multiple times.

Here: https://github.com/0x48piraj/fadblock/issues/206#issuecomment-2241160009
