### ISSUE TITLE
No longer blocking ads

### ISSUE THREAD

**Issue by Tired-Dancer** [0x48piraj/fadblock#219]
What the title says. I'm running Opera Gx and I keep getting ads. I don't know what could be causing this, because 2 days ago I was getting the ad blockers not allowed message, then it was working fine most of yesterday, and now it's not working at all. 

Nothing has changed on my browser/computer. No update or downloads or changes whatsoever

**Comment by 0x48piraj** [comment]
Logging out, clearing out the cookies and logging back in fixes the issue.

I have gotten some specific reports which I am investigating, so if there's some patch by YouTube, I will fix it and publish a new version soon.

**Comment by 0x48piraj** [comment]
### Just pushed the new update, 2.0 is coming!

To the loyal existing users, thank you for your support. Simply log in to your accounts, as I have securely migrated all your data, ensuring a seamless transition without the need for account creation or additional payments.

For those who have been using the extension for free, I appreciate your interest in our service. Please note that while you will no longer experience pop-ups, you will need to start a trial account to continue enjoying FadBlock. After the 7-day trial, a lifetime membership will be required to access all features.

Read the [project home](https://github.com/0x48piraj/fadblock) for more information.

Thank you for being part of our journey!

![](https://media.tenor.com/a7vXmLPB_DsAAAAM/ross-rachel.gif)

**Comment by 0x48piraj** [comment]
Move here: https://github.com/0x48piraj/fadblock/issues/196
