### ISSUE TITLE
YouTube endless refresh.

### ISSUE THREAD

**Issue by rekreator12e** [0x48piraj/fadblock#22]
When I try to watch the video, YouTube starts endlessly refreshing the page. I'm not using any other ad blockers, but I have that issue in the past (while using ad blockers)

**Comment by 0x48piraj** [comment]
Which browser, platform are you using, and can you dump the current DOM state so I can examine closely?

#### How to?
> Using the Web Inspector (F12), go to the Elements tab, right click on the `<html>` tag in your code and select `Copy`->`Copy outerHTML`. Then paste that into a new file and save.

**Comment by rekreator12e** [comment]
Sorry for not replying faster, but the issue persists. I  use Edge. I can't pause the ad, because the page just refreshes before I can do anything, and if I stop it from reloading, it's just a blank page. I found that I have to either clear my cookies(all, not just youtube for some reason). My ad blocker is paused on yt. Sometimes, it works after 3 reloads, sometimes after tens of reloads, and sometimes it doesn't.

**Comment by 0x48piraj** [comment]
This is very strange. Edge users are having problems in general. I honestly haven't tested a whole bunch in Edge but maybe try the new version which comes in the Chrome store and post if you stumble into the refresh problem again. Closing.

Reference: [How to Install Google Chrome Extensions in Microsoft Edge](https://www.howtogeek.com/411830/how-to-install-google-chrome-extensions-in-microsoft-edge/)
