### ISSUE TITLE
YouTube warning banner showing up as of yesterday

### ISSUE THREAD

**Issue by brianlevin83** [0x48piraj/fadblock#223]
YouTube is catching onto the ad blocker and the warning banner is showing up now. Started noticing it yesterday but you could simply refresh to bypass, but this morning you cannot. On the one hand this is helpful so I don't procrastinate from work, but on the other I think you should give this a look over. Thanks for all you do!

Chrome
Ventura 13.6.7
Version 127.0.6533.119 (Official Build) (arm64)

**Comment by maxsoup** [comment]
same for me, im using opera and its doing the same, although if i refresh a couple times it usually works but i still get the banner at least once per video, ik some ppl got their accounts banned for this so i hope this issue is solved soon

**Comment by maxsoup** [comment]
update, refreshing no longer works.

**Comment by wesleyhahaha** [comment]
same here， starting yesterday

**Comment by brianlevin83** [comment]
That seems to have worked so far for me today on my machine at my office, will test at home and use for a few days to confirm. Thanks!

**Comment by wesleyhahaha** [comment]
> Logging out - deleting your cache - logging back in to your YT account solves the issue for most, can you guys try and report back?
> 
> I am swamped in some stuff and FadBlock works for me flawlessly (so reproducing the bug has been hard) but I am investigating this issue and I hope a fix is finalized soon.

It works now, Thank you so much

**Comment by brianlevin83** [comment]
Well it WAS working the other day, but we're back to getting hit with the warning label again just a couple of days later. That, coupled with the frozen "skip screen" showing up as of late, it seems Youtube is changing something to try and circumvent the blocker.

**Comment by 0x48piraj** [comment]
Hey everyone, I’m currently working on a fix and I’m hopeful that a new version will be released this week!

**Comment by 0x48piraj** [comment]
### Just pushed the new update, 2.0 is coming!

To the loyal existing users, thank you for your support. Simply log in to your accounts, as I have securely migrated all your data, ensuring a seamless transition without the need for account creation or additional payments.

For those who have been using the extension for free, I appreciate your interest in our service. Please note that while you will no longer experience pop-ups, you will need to start a trial account to continue enjoying FadBlock. After the 7-day trial, a lifetime membership will be required to access all features.

Read the [project home](https://github.com/0x48piraj/fadblock) for more information.

Thank you for being part of our journey!

![](https://media.tenor.com/a7vXmLPB_DsAAAAM/ross-rachel.gif)

**Comment by uthomkirp** [comment]
make your fingerprint less unique with ONE extension and a not-uncommon build

**Comment by 0x48piraj** [comment]
Let's move here: https://github.com/0x48piraj/fadblock/issues/196
