### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by fivelow** [0x48piraj/fadblock#224]
Your extension pops up begging for money all the time and then it doesn't even work. It's basically the same as the ads on youtube, annoying and intrusive with no real value.

**Comment by Esh07** [comment]
Make sure disable any other ads blocker (including popup blocker), remove the `Friendly Adblock for YouTube` and then add the extension again from web store. Currently, it worked for me.

**Comment by 0x48piraj** [comment]
Hey everyone, I’m currently working on a fix and I’m hopeful that a new version will be released this week!

**Comment by 0x48piraj** [comment]
Ah, you're one of those, blocking 100 ads and asking an one-time contribution, in a nutshell, 100:1 is 1:1 to you? Fantastic!

Thanks @Esh07 for helping out, you're awesome!

Closing the issue.
