### ISSUE TITLE
Static advertising at the beginning of a video

### ISSUE THREAD

**Issue by Enkirch** [0x48piraj/fadblock#225]
Since today I see commercials in Germany at the beginning of the video, but only as a static picture, a timer runs in the upper right corner and in the lower right corner I have the “skip” button

Edit:
Now i also having a normal video ad at the beginning...

**Comment by SheeepsAreNice** [comment]
Also seeing this in the UK for the last couple of days. The ad is skipped but freezes on the final action button screen for between 5-10 seconds. It does eventually push past it.

<img width="1351" alt="Screenshot 2024-08-30 at 9 13 37 pm" src="https://github.com/user-attachments/assets/440e45fe-ce22-4ea8-8b50-aafe133312f8">

**Comment by brianlevin83** [comment]
Can confirm that I'm also seeing static ads as of the last day or two, and despite having cleared cache while logged out am occasionally getting the "Allows ads" warning popup.

**Comment by wesleyhahaha** [comment]
Yea, I also can't use it now in Australia.

**Comment by mike-matenkosky** [comment]
I see it too and I'm getting ads while watching. The ads do stop, but I have to press the "Skip" button. It does it on my Win 10 machine using Firefox or Chrome.

**Comment by 0x48piraj** [comment]
Hello everyone, I hope you’re all doing well. As @ckeene159 mentioned in a different thread, signing out, clearing cookies, signing back in can be quite helpful but only as a temporary fix.

Life has been tough lately, and it seems the same issue is now affecting my region too, just like many of you. This gives me the opportunity to debug and work towards a solution. I’ve been testing new patches with our internal testers from around the world over email, but progress has been a bit slow. Thank you for your patience.

**Comment by 0x48piraj** [comment]
Hey everyone, I’m currently working on a fix and I’m hopeful that a new version will be released this week!

**Comment by 0x48piraj** [comment]
### Just pushed the new update, 2.0 is coming!

To the loyal existing users, thank you for your support. Simply log in to your accounts, as I have securely migrated all your data, ensuring a seamless transition without the need for account creation or additional payments.

For those who have been using the extension for free, I appreciate your interest in our service. Please note that while you will no longer experience pop-ups, you will need to start a trial account to continue enjoying FadBlock. After the 7-day trial, a lifetime membership will be required to access all features.

Read the [project home](https://github.com/0x48piraj/fadblock) for more information.

Thank you for being part of our journey!

![](https://media.tenor.com/a7vXmLPB_DsAAAAM/ross-rachel.gif)

**Comment by 0x48piraj** [comment]
Let's move here: https://github.com/0x48piraj/fadblock/issues/196
