### ISSUE TITLE
Video stops playing

### ISSUE THREAD

**Issue by Lizardkingmr** [0x48piraj/fadblock#226]
The videos seems to be going fine sometimes, but sometimes the video will just stop playing, Most likely after blocking an ad.

**Comment by 0x48piraj** [comment]
Hello everyone, I hope you’re all doing well. As @ckeene159 mentioned in a different thread, signing out, clearing cookies, signing back in can be quite helpful but only as a temporary fix.

Life has been tough lately, and it seems the same issue is now affecting my region too, just like many of you. This gives me the opportunity to debug and work towards a solution. I’ve been testing new patches with our internal testers from around the world over email, but progress has been a bit slow. Thank you for your patience.
