### ISSUE TITLE
Adblockers violate TOS message... yet again.

### ISSUE THREAD

**Issue by LukeSaward1** [0x48piraj/fadblock#228]

**Comment by stoogeslap** [comment]
I hope the creator of FadBlock is still working of FadBlock. If this was opened five days ago and I am the first one to comment, I am worried. I just gave an bug issue report. I'm giving FadBlock 2 weeks to get things in gear before I uninstall the app and search for another solution to YouTube ads.

**Comment by 0x48piraj** [comment]
Hello everyone, I hope you’re all doing well. As @ckeene159 mentioned in a different thread, signing out, clearing cookies, signing back in can be quite helpful but only as a temporary fix.

Life has been tough lately, and it seems the same issue is now affecting my region too, just like many of you. This gives me the opportunity to debug and work towards a solution. I’ve been testing new patches with our internal testers from around the world over email, but progress has been a bit slow. Thank you for your patience.

**Comment by 0x48piraj** [comment]
Hey everyone, I’m currently working on a fix and I’m hopeful that a new version will be released this week!

**Comment by 0x48piraj** [comment]
### Just pushed the new update, 2.0 is coming!

To the loyal existing users, thank you for your support. Simply log in to your accounts, as I have securely migrated all your data, ensuring a seamless transition without the need for account creation or additional payments.

For those who have been using the extension for free, I appreciate your interest in our service. Please note that while you will no longer experience pop-ups, you will need to start a trial account to continue enjoying FadBlock. After the 7-day trial, a lifetime membership will be required to access all features.

Read the [project home](https://github.com/0x48piraj/fadblock) for more information.

Thank you for being part of our journey!

![](https://media.tenor.com/a7vXmLPB_DsAAAAM/ross-rachel.gif)

**Comment by mike-matenkosky** [comment]
How do I pay if I don't own a cell phone and I'm not signing up for Stripe?

**Comment by ckeene159** [comment]
At https://github.com/0x48piraj/fadblock it shows paypal link as https://www.paypal.com/paypalme/piyushella

When I did that a couple months ago (sent US $16) I got the following email from Piraj:

> I have added this email of yours so you can now log in and enjoy the lifetime membership!
>         
> Go to the FadBlock extension’s UI, or when the popup comes, you can click the make payment button, and then the new window will open, click on Login, use this email, you will be verified and be given unlimited access. If you don't know, you can now use this email of yours to use FadBlock on an unlimited number of devices, just follow the same instructions as above.

**Comment by mike-matenkosky** [comment]
> At https://github.com/0x48piraj/fadblock it shows paypal link as https://www.paypal.com/paypalme/piyushella
> 
> When I did that a couple months ago (sent US $16) I got the following email from Piraj:
> 
> > I have added this email of yours so you can now log in and enjoy the lifetime membership!
> > Go to the FadBlock extension’s UI, or when the popup comes, you can click the make payment button, and then the new window will open, click on Login, use this email, you will be verified and be given unlimited access. If you don't know, you can now use this email of yours to use FadBlock on an unlimited number of devices, just follow the same instructions as above.

I'll just wait until the new version rolls in and see what happens.

**Comment by 0x48piraj** [comment]
@mike-matenkosky, You don't have to sign up for Stripe. It's the most secure and reliable payment processing service there is.

You can try the trial version, and if it doesn’t meet your needs, you can decide what to do next.

If you’re facing financial constraints and prefer not to pay, feel free to email me, and I can add you for free as a gesture of goodwill.

**Comment by 0x48piraj** [comment]
Let's move here: https://github.com/0x48piraj/fadblock/issues/196
