### ISSUE TITLE
YouTube is fighting back, they found a solution... I might stop using fadblock

### ISSUE THREAD

**Issue by stoogeslap** [0x48piraj/fadblock#229]
So it appears YouTube has found a way to to make viewers who use fadblock and other extensions like it wait afterwards for 5-10 seconds, staring at an almost solid color blank screen or a massive logo of the company, with the logo of the sponsor that was just skipped past in the center of the screen, with a 5 second timer at the bottom-right of the screen. Or the viewer can just wait for the timer and stair at the logo and wait for the zipped through add to automatically jump out of the ad... sometimes there is a second one (unfortunately). I have attached a screenshot as proof.

If this is not addressed, or I am not told it will be fixed in X amount of days (I will wait up to two weeks, I think that is adequate to give for it to be fixed), I will stop using fadblock all together and look for another solution. It was great while it lasted as it was a great temporary solution.  

I do not know why, but I had to resign up w/ GitHub to give this support under my gmail account (which is what my extension was downloaded under), but my previous communications might've been made through my Yahoo email account, warp_______er@yahoo.com.

I am hoping you can get back to me sometime today w/ an update w/ any information... such if you are aware of this... If you are aware of it, what steps are being done. What can be done, if anything... I appreciate all that you have done in the past and are doing; I just hope this isn't the end.
![fast forward - youtube is fighting back](https://github.com/user-attachments/assets/28822aa5-0181-413a-905e-cd2dc99dcfab)

**Comment by 0x48piraj** [comment]
Closing this as duplicate as you replied on a different thread having the same issue.
