### ISSUE TITLE
Youtube ads are playing at 1x speed and without video

### ISSUE THREAD

**Issue by 9qwer1** [0x48piraj/fadblock#24]
Installed fadblock and was working as expected for ~ 1 week - Youtube ads would load, and then be promptly skipped. Logged in today and found that youtube ads are loading and playing at 1x speed, and without video - only sound.
![Screenshot 2023-10-25 at 12 07 24 PM](https://github.com/0x48piraj/fadblock/assets/17186411/9b7ea287-6e19-4339-815a-cfceb44110e6)

**Comment by 0x48piraj** [comment]
Can you dump the current DOM state so I can examine closely?

#### How to?
> Using the Web Inspector (F12), go to the Elements tab, right click on the `<html>` tag in your code and select `Copy`->`Copy outerHTML`. Then paste that into a new file and save.

**Comment by 9qwer1** [comment]
> Can you dump the current DOM state so I can examine closely?
> 
> #### How to?
> > When FadBlock doesn't work on a specific ad, while the ad is showing, pause the ad, then using the Web Inspector (F12), go to the Elements tab, right click on the `<html>` tag in your code and select `Copy`->`Copy outerHTML`. Then paste that into a new file and save.
[DOM_state.txt](https://github.com/0x48piraj/fadblock/files/13178416/DOM_state.txt)

Sure thing - See attached

**Comment by 0x48piraj** [comment]
Thank you @9qwer1, I found the new patch Google implemented and am working on a new release which will work, in addition, it's going to successfully block out survey ads as well as homepage sponsored banners.

But it seems like you're using SponsorBlock, most likely, some of the extensions are messing with the video as black screen is a general problem of adblockers, this issue cannot happen via FadBlock as the extension does not tweak the source URL in any way.

**Comment by 0x48piraj** [comment]
Adressed in https://github.com/0x48piraj/fadblock/commit/acb920a8040c1ce2a00c9c147b8307ee19bc6c65. Closing.
