### ISSUE TITLE
Can't open the chapter list

### ISSUE THREAD

**Issue by EthanWinters2885** [0x48piraj/fadblock#25]
**Describe the bug**
If you try clicking on a chapter name, the list doesn't appear.

**To Reproduce**
1. Enable the extension
2. Click on the chapter name (the one with arrow next to it)
3. nothing happens

**Expected behavior**
The chapter list is supposed to open

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version: 1,3

**Additional context**
The one under the video progress bar thing, that would say "View Chapter"

**Comment by 0x48piraj** [comment]
What's a chapter list? I don't understand, can you please post a screenshot?

**Comment by Grg76** [comment]
I have the same problem, here is a screenshot.   When i disable the extension, then the Chapter list is visible. When enabling, it is not visible, maybe it is recognized as an ad.
The Chapter list is at the right side named "Fejezetek"  ( In Hungaraan language :) )

![Névtelen-1](https://github.com/0x48piraj/fadblock/assets/149167462/862e0766-86e1-4ee1-a40d-a81954ef8ec4)

**Comment by 0x48piraj** [comment]
I got it, thank you for informing, I will work on it!

**Comment by 0x48piraj** [comment]
The upcoming version will fix this issue. Closing.

**Comment by EthanWinters2885** [comment]
Thank you! Yea that's what I was mentioning lol
