### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by lexscs** [0x48piraj/fadblock#26]
After the 26-10-2023 update, the extension stopped working

**Comment by 0x48piraj** [comment]
Can you test the [newest version](https://github.com/0x48piraj/fadblock/releases/tag/1.3) and test it out until the stores get updated with 1.3?

**Comment by lexscs** [comment]
I just tested it and it's still the same. Here in Brazil it is 10/27/2023, 11:20am

**Comment by 0x48piraj** [comment]
Are you using 1.3 @lexscs?

**Comment by lexscs** [comment]
Yes, and yesterday I even looked here to see if there was a new update. But I noticed that other users are also having the same problem!

**Comment by 0x48piraj** [comment]
I'm sure a certain adblocker (whether in-built or external) is acting up. FadBlock working in a private window also confirms that statement as extensions aren't available to the incognito mode by default. And by using the word "private", I suspect you're not using Chrome (Firefox and Brave for example have in-built adblockers which are also getting detected).

**Comment by lexscs** [comment]
I installed the extension in Firefox as I couldn't find it in Opera. I have Chrome, but I use it for other things. I will check this question about Firefox adblock, thanks
