### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by Avedsand** [0x48piraj/fadblock#31]
Its not really a bug but every since I got this extension my YouTube videos have been lagging out more and started lagging during videos which rarely happens with this computer YouTube.

**Comment by Avedsand** [comment]
Google Chrome Version 118.0.5993.90 (Official Build) (64-bit)
Windows 10 Home 64-bit operating system, x64-based processor

**Comment by Avedsand** [comment]
nvm its workin fine now

**Comment by 0x48piraj** [comment]
Lag is not a possible outcome of FadBlock.
