### ISSUE TITLE
"Show transcript" does not work

### ISSUE THREAD

**Issue by placetne** [0x48piraj/fadblock#32]
**Describe the bug**
"Show transcript" does not work when FadBlock is installed and enabled. If you disable FadBlock, "Show transcript" does work.

**To Reproduce**
1. Go to any YouTube video with transcripts
2. Click on "Show transcript"
3. The transcript panel not appear.

**Expected behavior**
After clicking on "Show transcript", the transcript shows.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome, Firefox
 - Version: Latest

**Comment by 0x48piraj** [comment]
Similar to https://github.com/0x48piraj/fadblock/issues/25. Currently working on a fix.

**Comment by 0x48piraj** [comment]
The next upcoming version will fix this issue. Closing.
