### ISSUE TITLE
Speed up the YouTube Music ads

### ISSUE THREAD

**Issue by IvanLo0725** [0x48piraj/fadblock#33]
I hope to speed up the ads on YouTube Music. Currently, when I listen music on YouTube Music, the ads still play in full, and ad blockers consider youtube.com and music.youtube.com as the same domain, so they can only be enabled or disabled at the same time.

**Comment by 0x48piraj** [comment]
The next version will expand onto YouTube Music, will have a block counter including some other niche features as well as proposed bugfixes. As this project has demanded a substantial amount of time, the repository will transition to an open-core model for ongoing maintenance and updates.
