### ISSUE TITLE
improve performance and disable reflash after installed

### ISSUE THREAD

**Issue by meisken** [0x48piraj/fadblock#34]
Run the script every 0.1 second something may cause lagging on my old PC. 

For better performance, I changed the setTimeout to MutationObserver. It can reduce a lot of the number of runs. Should i make a pull request?
![image](https://github.com/0x48piraj/fadblock/assets/38470704/33817720-7c30-4574-aa67-ba507ba513c1)

Also, I would like to disable reflashing all the YouTube tabs after installed. Because all the YouTube videos will play at the same time after reflash. it's so annoying when I have multiple YouTube tabs.

**Comment by 0x48piraj** [comment]
The reloading of tabs issue was already addressed in the last update. The new version upcoming will be employing MutationObserver with a polyfill to address old browsers, which was the reason for not implementing MO at the start, i.e. compatibility. The next version will expand onto YouTube Music, will have a block counter including some other niche features as well as proposed bugfixes. As this project has demanded a substantial amount of time, the repository will transition to an open-core model for ongoing maintenance and updates.

Note: The `taimuRipu` was a reference to "time leap" ;)
