### ISSUE TITLE
Video pages not loading

### ISSUE THREAD

**Issue by eric-ao** [0x48piraj/fadblock#35]
**Describe the bug**
When trying to watch a video, the page itself wont load. It will take sometime, it can be seconds or a couple minutes. Once it loads, the video plays fine and everything seems normal, even the adblock works as intended.

**To Reproduce**
1. Go to Youtube
2. Click on any video
3. See error

**Expected behavior**
The video page loads instantly.

**Screenshots**
![image](https://github.com/0x48piraj/fadblock/assets/60254579/bca94bd4-bd2d-47c9-bb15-582b8bb268d8)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 118.0.5993.118 (64bits)

**Additional context**
I tried uninstalling the adblock and it fixes the problem (after a few minutes aswell, maybe something related to cache?), so I'm assuming its related to the adblock itself.

**Comment by 0x48piraj** [comment]
Clearly, in the screenshot itself, you can see that some xyz extension's main.js was not loaded. That's your potential culprit.

Please read FAQ, don't stack adblockers.
