### ISSUE TITLE
Disruptive UX on updates

### ISSUE THREAD

**Issue by gund** [0x48piraj/fadblock#4]
I've noticed that this extension will try to reload any YT tab whenever it gets updated in the background or even when browser itself get's updated which makes no sense and is quite disruptive for a UX:
https://github.com/0x48piraj/fadblock/blob/2b26707f8c8054a4941ee69ac0757d7955055ca2/src/chrome/js/background.js#L17-L23

Can you consider removing this option, and just auto reloading on install as this is the only time when reloading is acceptable-ish, even tho I would argue that is also not desirable in some cases, like you would like to note a timestamp of a video you are watching before reload (yes if your YT history is off it will not even remember your last played time geez).

Maybe this option can also be configurable from the extension management so users can opt-in for auto-update as it is right now but that is not that critical I think, the most important is to remove disruptive behavior first I think.

Thanks for the extension btw!

**Comment by 0x48piraj** [comment]
I added the following subroutine after listening to several responses (people not restarting or reloading after installing the extension). It only reloads when the extension is installed/updated so I don't think it's much of a hassle for end users.
