### ISSUE TITLE
Ads are not skipped

### ISSUE THREAD

**Issue by Driftlife** [0x48piraj/fadblock#40]
Google Chrome: Version 118.0.5993.118 (Official Build) (64-bit)
Windows 10 Home, 64-bit operating system, x64-based processor

I tried logging out of my google account and the problem disappeared. It appeared again when I switch back to the main account.

![111未命名](https://github.com/0x48piraj/fadblock/assets/149383496/32737fc2-847e-4494-bdd4-40b95c5ef14c)

Only Category 1: Ads visible on the home page have been eliminated

**Comment by Driftlife** [comment]
How do I provide DOM state

**Comment by imjeffreylee** [comment]
I have the same issue, ads are not skipped when I am logged in. Works fine when I'm not logged in.
Chrome version: 118.0.5993.118
Windows 11 Home, 64 bit

**Comment by 0x48piraj** [comment]
I'm investigating that issue currently.

**Comment by samliu23** [comment]
same for edge
version: 118.0.2088.76 
Windows 11 Home, 64 bit
[Copy.outerHTML.txt](https://github.com/0x48piraj/fadblock/files/13210497/Copy.outerHTML.txt)

**Comment by CloudOKC** [comment]
same on Firefox after Firefox request new authority
win10 pro 21H2, Firefox 119.0 x64

**Comment by Grg76** [comment]
After updating to V1.5 ads are not skipped, and sponsored content is visible too.  When i downgrade to the V1.3 the its working fine again.

![Névtelen-1](https://github.com/0x48piraj/fadblock/assets/149167462/1dbf6a34-8290-4c84-a54e-39705e383fac)
![Névtelen-2](https://github.com/0x48piraj/fadblock/assets/149167462/02519cc5-8f28-4278-8e56-364f7777d9ba)

**Comment by 0x48piraj** [comment]
Did you refresh the browser after updating to v1.5? @Grg76 

If so, can I get a screenshot of the FadBlock UI screen?

**Comment by Grg76** [comment]
Yes, i closed and restarted my browser (Firefox 119.0). I did it now again plus uninstalled and reinstalled Fadblock, but the ads still there. 


![Névtelen-1](https://github.com/0x48piraj/fadblock/assets/149167462/177968b3-fa41-41b2-aa01-69de22ac8e2d)

**Comment by Weilun0812** [comment]
@0x48piraj 
My problem is that it doesn't work when I use my main account to watch, but it works when I switch to other accounts.

**Comment by Shadowized** [comment]
I have the same problem, I updated last night and this morning I load a video and instantly see an ad and it has "undefined" in the menu. Downgraded to 1.3 for the time being.

**Comment by 0x48piraj** [comment]
I am working on it. Seems like a few things are not being initialized properly as well as there are some performance issues.

**Comment by 0x48piraj** [comment]
@Grg76 (a big shoutout for the detailed report), @Shadowized you guys can update the version to 1.6 manually, an urgent fix was rolled out just now.

**Comment by 0x48piraj** [comment]
For Chromium users, v1.5 will fix all the issues. Please wait till Chrome reviews and approved the new codebase. Closing.

**Comment by Shadowized** [comment]
Seems to be working on skipping ads after restarting the browser, but it causes a severe render delay on loading youtubes subscription page so I dunno.

**Comment by imjeffreylee** [comment]
@0x48piraj Do we know long does it usually take Google to approve it?

**Comment by 0x48piraj** [comment]
@imjeffreylee It usually takes around 24-48 hours.

**Comment by Driftlife** [comment]
Have you changed the product name? Google only has version 1.3.

**Comment by JeffreyLee-Pricer** [comment]
@Driftlife Yeah that's why I'm asking
