### ISSUE TITLE
OperaGx youtube detect Fadblock and prevent watching vid. works fine on google chrome for me for now.

### ISSUE THREAD

**Issue by Meza85** [0x48piraj/fadblock#41]
OperaGx ads are not blocked anymore youtube detect that im using an adblocker
![image_2023-10-30_153255432](https://github.com/0x48piraj/fadblock/assets/149430540/90ce051d-c509-4c5a-a4dc-23feed605c1f)

**Comment by 0x48piraj** [comment]
Disable uBlock Origin and other adblockers. Check for Opera's inbuilt adblocker. They are getting detected NOT FadBlock.

**Comment by Meza85** [comment]
thanks man it works ! nice work on this you inspiring me to go follow some
studies to learn all this coding stuff to make my own stuff when new
problem arise from these filthy ad infested popular site want to grab our
money of greed, anyway thanks man for the reply

Le lun. 30 oct. 2023 à 19:06, Piyush Raj ***@***.***> a
écrit :
