### ISSUE TITLE
Ad is not skipped #2

### ISSUE THREAD

**Issue by sskras** [0x48piraj/fadblock#45]
I installed the extension yesterday. It seemingly worked (by allowing only 1s of an ad to be played).

Today ads are not skipped for me too.  This is the HTML i managed to copy out: [Copy-outerHTML-for-v=GmxegKvxvJM-by-sskras.txt](https://github.com/0x48piraj/fadblock/files/13220341/Copy-outerHTML-for-v.GmxegKvxvJM-by-sskras.txt)

**Comment by 0x48piraj** [comment]
Can you also post the screenshot of the extension, or, confirm if it looks something like [this](https://github.com/0x48piraj/fadblock/issues/40#issuecomment-1786946044)?

**Comment by sskras** [comment]
Will this do?

![image](https://github.com/0x48piraj/fadblock/assets/7887758/bc2e2db6-8091-4c57-aecd-d5fea79f3b69)

I also use **uBlock Origin** here, but it's disabled for Youtube now:

![image](https://github.com/0x48piraj/fadblock/assets/7887758/43f8f12c-28f8-4588-bf12-0f31e71594c9)

**Comment by 0x48piraj** [comment]
Google must have pushed a new patch. v1.5/6 will hopefully be released soon after the Chrome team approves the new codebase.

For now, if you use Firefox as well, you can use the v1.6 over https://addons.mozilla.org/en-US/firefox/addon/fadblock/

**Comment by sskras** [comment]
Thanks for the workaround.

I installed FadBlock 1.6 on Firefox 96.0.3 (64-bit). The ad is not blocked here either:

![image](https://github.com/0x48piraj/fadblock/assets/7887758/0f98ad88-5d20-4771-b6c1-2ca242bee4e6)

Here is my HTML: [Copy-outerHTML-for-v=GmxegKvxvJM-by-sskras-Firefox.txt](https://github.com/0x48piraj/fadblock/files/13228439/Copy-outerHTML-for-v.GmxegKvxvJM-by-sskras-Firefox.txt)

Should I file a new issue?

**Comment by sskras** [comment]
Thanks for the workaround.

I installed FadBlock 1.6 on Firefox 96.0.3 (64-bit). Some ad was not blocked here either:

![image](https://github.com/0x48piraj/fadblock/assets/7887758/609302a9-67f3-43fc-aec3-3e80832512ca)

Here is my HTML: [Copy-outerHTML-for-v=GmxegKvxvJM-by-sskras-Firefox.txt](https://github.com/0x48piraj/fadblock/files/13228547/Copy-outerHTML-for-v.GmxegKvxvJM-by-sskras-Firefox.txt)

Should I file a new issue?

**Comment by 0x48piraj** [comment]
I will investigate the issue, but it seems like there's been some compatibility issues.
