### ISSUE TITLE
Questionable access to expensionpay.com

### ISSUE THREAD

**Issue by SolenoidMan** [0x48piraj/fadblock#46]
The addon is now making unnecessary access requests to extensionpay.com, I've disabled addon until removed, there's no expalantion why this is there all of a sudden and extremely worrying

**Comment by 0x48piraj** [comment]
It's there in the announcement, what do you mean? It's on the release notes as well.

**Comment by 0x48piraj** [comment]
Seems like there's been a lot of confusion, reopening the original thread https://github.com/0x48piraj/fadblock/issues/42, closing this issue, and will be adding a more explicit notice.
