### ISSUE TITLE
Ads Not Skiped

### ISSUE THREAD

**Issue by toxiiqu** [0x48piraj/fadblock#47]
Yesterday the ads were skipping fine, but thing were unable to autoplay and the "pop out" feature on Firefox videos was not working. With today's update it seems like the pop out feature is back and videos can auto play but ads are not skipping. 
 
![10-31 YT ADS](https://github.com/0x48piraj/fadblock/assets/149542582/36eaf89c-a92c-4333-bd7b-94a86d5bf35a)

**Comment by 0x48piraj** [comment]
Can you update the version to 1.6 manually, an urgent fix was rolled out just now.

**Comment by toxiiqu** [comment]
Hello I updated to 1.6 and the ads are still not being skiped on my end.

**Comment by 0x48piraj** [comment]
Uninstall and install the extension again. It will work. I am so sorry for the trouble caused @toxiiqu .
