### ISSUE TITLE
Skipped the actual video

### ISSUE THREAD

**Issue by yikwongji** [0x48piraj/fadblock#48]
I am using Opera. Sometimes, when skipping the ad, it also skips a part of the actual video. For instance, if the ad is 1:30 minutes long, it may also skip the video for 1:30 minutes. Additionally, sometimes it does not skip the ad.

**Comment by 0x48piraj** [comment]
Can you provide a sample video where it happened so I can investigate that issue?

**Comment by yikwongji** [comment]
> Can you provide a sample video where it happened so I can investigate that issue?

https://youtu.be/PIz4rLQNanw

**Comment by giovanniro98** [comment]
Same issue as well

**Comment by Grg76** [comment]
Same skipping issue on Firefox too, with all versions of Fadblock 1.3, 1.5, 1.6

**Comment by 0x48piraj** [comment]
v.2.0 fixes all the issues while black screen is not an underlying issue of FadBlock. Closing.
