### ISSUE TITLE
Transcript Not Working with Extension Enabled

### ISSUE THREAD

**Issue by nerdyclass101** [0x48piraj/fadblock#49]
The extension skips through ads just fine, but it unfortunately also prevents video transcripts from loading when enabled. I've tested to make sure, and when the extension is off I can pull up the transcript, but when the extension is on clicking the transcript button does nothing. This extension is wonderful and the issue's not that big of a deal, but if it could be fixed it would be perfect! Thanks!

_**I've tried it in Firefox Developer Edition and Google Chrome, and the issue is the same on both_

**Comment by 0x48piraj** [comment]
The Firefox version should fix the issue, and soon Chrome will also be updated with the new version.
