### ISSUE TITLE
Prototype pollution

### ISSUE THREAD

**Issue by gund** [0x48piraj/fadblock#5]
This plugin uses technique called "prototype pollution" which is considered anti-pattern and may cause forward compatibility issues in the future if similar methods would be added by the language itself:
https://github.com/0x48piraj/fadblock/blob/2b26707f8c8054a4941ee69ac0757d7955055ca2/src/chrome/js/content.js#L39-L42

There is no real reason to do that really you can just define your own function and call it directly instead of adding it to global `document` object.

**Comment by 0x48piraj** [comment]
Sure, I'd take a look!
