### ISSUE TITLE
Cannot figure out how to purchase license

### ISSUE THREAD

**Issue by ChocoChopin** [0x48piraj/fadblock#51]
Raj, my friend, I appreciate everything you do and would love to purchase a license for your superior adblock solution--one that allows me to enjoy YouTube without depriving my favorite creators of ad revenue. It's truly a win-win. I honestly don't even miss uBlock Origin (on YouTube, at least) and won't be going back to it for YouTube.

But I cannot _for the life of me_ figure out how I'm meant to purchase a license for Fadblock. I see the popup about the trial period ending, and as far as I can tell from your release notes, the extension itself is supposed to interact with extensionpay for the sake of the license in question, but there appears to be no link, no nothing, to that end. GitHub offers ways to sponsor you, as does your homepage, but none of these indicate any kind of license purchase for Fadblock.

Please just let me know what I should do.

**Comment by 0x48piraj** [comment]
I am so sorry to hear that when you go to the FadBlock's UI, isn't there a screen something like this?

<p align="center">
<img src="https://github.com/0x48piraj/fadblock/assets/5800726/4e43f99b-5fec-4bfd-9eb7-b0eaeda6a29d"/>
</p>


> **Note:** I am testing a lot of things after getting a lot of backlash, what the community wants, is the price point justified, is the hard paywall a good choice, or whether it should run even after the trial ends but asks for the license sometimes rather than on each video, the performance and compatibility issues, and most of all, should I even bother maintaining and improving this or it's a lost cause. So, I'm grateful for those kind words and the constructive feedback.

**Comment by ChocoChopin** [comment]
Ah, seems mine is bugged, in that case. I only see this:
![image](https://github.com/0x48piraj/fadblock/assets/53260343/28f90e93-cdef-4c70-becd-fe0d1d222c27)

and then this:
![image](https://github.com/0x48piraj/fadblock/assets/53260343/0f82cff8-8bb3-4fbc-82cf-e982fb312b10)

I'll try uninstalling and reinstalling to see if that helps.

**Comment by ChocoChopin** [comment]
No change, though I haven't yet hit the 50-ad limit, which reset after the install and will take some time. I'm assuming the option to buy a license should be there either way. For what it's worth, I'm on Firefox.

Regarding your note: someone like me is happy to pay for a license, especially when the asking price is so small. I really can't speak for other users, and a lot of projects I love use the unlimited-free-trial model with seeming great success. Difficult decision indeed, hard to get a sense of how everybody feels and what they want.

**Comment by 0x48piraj** [comment]
Can you update to the new v2.0 and see if it works? (I changed it to the unlimited-free-trial model with a better UI and other changes). For some people, it seems the new Observer API is not working and the ads are not skipping, can you confirm if the v2.0 works effectively?

**Comment by 0x48piraj** [comment]
Seems like it's been fixed. Just update to the newest version.
