### ISSUE TITLE
V2.0 not skipping ads

### ISSUE THREAD

**Issue by Grg76** [0x48piraj/fadblock#53]
Updated today to 2.0 but it don't works, i tryed it too on a fresh Firefox install with no other addons, installed and uninstalled the addoin, restarted the browser sometimes, but no changes.  I don't know but the v1.3 was the last good working one, since i always messed up with the newer versions :( 

Here is a screenshot, and a -i hope usefull- DOM state:
 
![fadblok](https://github.com/0x48piraj/fadblock/assets/149167462/f47fa193-9898-406a-a861-aaa8da58e9c5)

[outerhtml.txt](https://github.com/0x48piraj/fadblock/files/13239531/outerhtml.txt)

Thank you for your work so far

**Comment by igorruckert** [comment]
Same here

**Comment by 0x48piraj** [comment]
Thank you very much for the detailed report, don't worry, it will get fixed. The newer codebase is more efficient but it seems like YouTube simultaneously released a patch OR there's been compatibility issues.

I will investigate and quickly update the extension until it becomes stable again. Don't worry.

**Comment by Grg76** [comment]
I use the newest Firefox 119.0

**Comment by 0x48piraj** [comment]
It works as said on the newest version, and it's not the common 'undefined' error as well.

I will try to investigate more, for the time being, switch to Chrome (if possible).

**Comment by Grg76** [comment]
I tried it today on Chrome, as the V2 was available, but unfortunately it does not work for me, same as with Firefox in my first post here, ads are playing, and the counter stays on 0 :(  

And i dont use any other addons on Chrome, since i generally not using Chrome. The only difference was, that Youtube in Chrome is not slowing down with Fadblock like in Firefox. (About many other people are complaining)
