### ISSUE TITLE
YouTube Patched The Current Version

### ISSUE THREAD

**Issue by ItsTepsu** [0x48piraj/fadblock#55]
I don't have any other ad blockers, youtube has added detection for the current version.
![image_2023-11-02_165444777](https://github.com/0x48piraj/fadblock/assets/149718500/97725918-9658-452e-ac91-61c7588fc223)

**Comment by ItsTepsu** [comment]
Turns out one of my other extensions was triggering the adblocker thing. Still no idea why because it doesn't block ads lol

**Comment by 0x48piraj** [comment]
Can you tell which extension as it so I can add it on the FAQ?

**Comment by ItsTepsu** [comment]
It was just something my friend made for fun, not something public
