### ISSUE TITLE
Not Working for Ads Placed in the Middle of the Video

### ISSUE THREAD

**Issue by RazeBerry** [0x48piraj/fadblock#57]
I have a Firefox 119 with the 2.0 version of the extension as the only AdBlock. It works regularly unless I have to watch a longer video, which there will still be Ads unfortunately. I can get rid of it by refreshing the page but it is annoying. Thank you for the work you have done.

**Comment by 0x48piraj** [comment]
Hey @RazeBerry.

Have you received a popup notification from FadBlock (which should appear after blocking more than 50 Ads)?

**Comment by RazeBerry** [comment]
<img width="325" alt="Screenshot 2023-11-03 at 14 37 35" src="https://github.com/0x48piraj/fadblock/assets/28079152/9d157a6d-fc12-45a1-841a-f9da592ef7bf">

**Comment by 0x48piraj** [comment]
This is not good, uninstall and reinstall the extension to make it work consistently.

Note: The extension is totally free but after 50 ads, it asks for a one-time contribution (works even if you don't want to pay, cancel the popup, refresh the tab).
