### ISSUE TITLE
Not-very-maintainable™ codebase

### ISSUE THREAD

**Issue by gund** [0x48piraj/fadblock#6]
This extension has the exact same implementation for all three different browsers currently: [chrome, firefox and opera](https://github.com/0x48piraj/fadblock/tree/2b26707f8c8054a4941ee69ac0757d7955055ca2/src).

This is of course fine for the beginning but as you will try to maintain this project it will become harder and harder to do so and keep track of changes in all 3 implementations. Also if time will come for another implementation it will add even greater complexity for maintenance.

I would suggest extracting the main extension logic into a reusable code which does not depend on any specific browser extension APIs and then linking it in specific extensions.

If you like I would gladly help you with refactoring as this change most likely will have to introduce a proper build step using something like rollup or vite (not sh/bash).

**Comment by zettlrobert** [comment]
i second that.

also currently you select the classes the typicall ads are rendered in by a staitc name, based on experience in a different adblocking project I recommend a simple way to update these string values from a centralized location (maybe even community based 'blacklist')

at some point they can also start to generated unique identifier classes or append hases to the injected class (similar to css modules) to make it more difficult to select said classes.

**Comment by gund** [comment]
Sounds great, I will try to make a PR on the weekend with some refactoring.
