### ISSUE TITLE
Chapters function won't work after enable the extension

### ISSUE THREAD

**Issue by ajRicky** [0x48piraj/fadblock#62]
The chapter function doesn't show up when clicked on it, nothing shows up on the right-hand side.
![20231104002237](https://github.com/0x48piraj/fadblock/assets/23473982/47c4563d-29a1-4910-8bd4-5deca5db97e6)

**Comment by 0x48piraj** [comment]
Are you on the Chrome? If's that's the case, please wait for the new update which will fix this issue.

**Comment by 0x48piraj** [comment]
Are you on the Chrome? If that's the case, please wait for the new update which fixes this issue.
