### ISSUE TITLE
YT is still detecting ad-blockers

### ISSUE THREAD

**Issue by askhati** [0x48piraj/fadblock#64]
YT still gives me the "You are using an ad-blocker" screen, even with Fadblock present. Fadblock is the only blocker I have installed, so it's definitely not a multi-blocker conflict. I also have Malwarebytes running.

Edit: am using Chrome.

**Comment by Maniacsan** [comment]
Fadblock is still working for me.
I'm using Firefox and made sure my adblocker is not blocking YT.

**Comment by harkai84** [comment]
Fadblock works well with Google Chrome.

**Comment by askhati** [comment]
> Fadblock is still working for me. I'm using Firefox and made sure my adblocker is not blocking YT.

I'm not sure how your comment is meant to help me?

**Comment by Maniacsan** [comment]
> > Fadblock is still working for me. I'm using Firefox and made sure my adblocker is not blocking YT.
> 
> I'm not sure how your comment is meant to help me?
> 

Try turning off Malwarebytes and see if that works.

**Comment by 0x48piraj** [comment]
Malwarebytes has an inbuilt adblocker. You got to figure out who to whitelist YouTube (if you don't want to lose out on web security features)
