### ISSUE TITLE
Not working specifically for Opera GX video ads

### ISSUE THREAD

**Issue by YellowBoi11** [0x48piraj/fadblock#65]
It's exactly how it sounds. I can't get fadblock to work for video ads. I've tried several different versions of fadblock all without Opera Ad Blocker, I've tried to install it from the chrome extensions store as well as unpacking it, and I've gone as far as to remove every other extension I have and purge it completely from my computer. It will still not block video ads. I also have a version of firefox that I use for college that I installed fadblock on and it works perfectly fine. I assume I've done something horribly wrong and would just like some more suggestions on what to change. Thank you!

**Comment by 0x48piraj** [comment]
So it seems you don't have the inbuilt Opera adblocker running which is a good sign.

I haven't thoroughly tested it over Opera GX to be completely honest, can you give me the version you're using and I will try to reproduce this issue and report back to you?

**Comment by bratan997** [comment]
it's working for me, i'm using opera gx LVL5 (core: 102.0.4880.117) with chromium ver 116.0.5845.188
sometimes the ads still showing but it automatically skips after a second

**Comment by YellowBoi11** [comment]
I have the identical version unfortunately. But I did notice it blocks banner and homescreen ads. Meaning it's only the video ads that continue to play. Would something like windows defender possibly get in the way, or maybe my cache?

**Comment by YellowBoi11** [comment]
I also noticed it is tagged as a service worker, but is inactive most of the time. I'm not familiar with how browser extensions work and if this even has anything to do with it being non-functional , but I'm grasping at straws by this point.

**Comment by YellowBoi11** [comment]
After some fiddling and a lot of file spelunking, 2.0 fixed it for some reason. This is no longer an issue. Have a nice life Piyush if you read this.
