### ISSUE TITLE
I would pay fadblock pro but ...

### ISSUE THREAD

**Issue by harkai84** [0x48piraj/fadblock#68]
Hey,
i would pay for fadblock pro but i dont have a Credit card.
Maybe you can give PayPal a try.

**Comment by 0x48piraj** [comment]
Here's the PayPal: https://www.paypal.me/piyushella

I will manually add you as a lifetime member.

**Comment by harkai84** [comment]
I am on EU so i can send you the money in €.
Is 6 Euro ok?
And which account will you add me manually?

**Comment by 0x48piraj** [comment]
I have added your email, when you get the popup, 

Go to the FadBlock extension’s UI, click the make payment button, and then the new window will open, click on Login, use your email, and you will be verified and given unlimited access.

**Comment by harkai84** [comment]
Thank you so mutch. If you want you can remove this topic.
Works perfect.

**Comment by gotexis** [comment]
there is a userscript version available in the repository you can use in userscript plugins (tampermonkey etc.) so you don't hav eto pay

**Comment by 0x48piraj** [comment]
Closing the issue then @harkai84.
