### ISSUE TITLE
not working in tandem with Enhancer for YouTube extension

### ISSUE THREAD

**Issue by phpmoli** [0x48piraj/fadblock#7]
When Enhancer for YouTube is active, the nagging screen appears, when Enhancer for YouTube is disabled, the nagging screen does not appear. Reproduced only on 1 system, needs others.

Not sure if this should be fixed here, or at Enhancer for YouTube, or even if you want to fix this, and start a never ending compatibility chase, but Enhancer for YouTube is used by a million users. So it's up to you if you want to say "fuck off".

Thanks for your work.

**Comment by phpmoli** [comment]
Sorry, forgot the link https://chrome.google.com/webstore/detail/enhancer-for-youtube/ponfpcnoihfmfllpaingbgckeeldkhle

**Comment by 0x48piraj** [comment]
YouTube is detecting that extension, not this one. So is the case with other adblockers.

For other adblockers, you can add _youtube.com_ to the exception list for domains on other adblockers (uBlock Origin, AdBlock) and then download fadblock to override regular adblock being prioritized on YouTube while the conventional adblocker will work across the remainder of the Internet.

I don't think we can do much if a specific extension made for YouTube is getting detected :(

**Comment by phpmoli** [comment]
You are right, for some reason, i had "block ads" turned on in that extension too besides ublock, i already disabled ublock, but didnt know about this. Disabling adblock in the Enhancer extension fixed it, everything working. Sorry for the needless ticket.
