### ISSUE TITLE
***UNABLE TO DISABLE EXTENSION***

### ISSUE THREAD

**Issue by bigjoncoop** [0x48piraj/fadblock#72]
Windows 11
Chrome - Latest version
Fadblock - Latest version

After installing the Fadblock extention, it caused a long delay when loading new videos on YouTube.

I disabled the extension and now there is still a very long delay loading videos. After the long delay it's showing a still image of the ad and the "skip ad" button...

Has anyone else experienced this issue?

Is there a solution to completely remove this extension and all of its adverse effects? Or should I just completely uninstall Chrome and reinstall making sure not to reload the extension?

**Comment by Eustella0510** [comment]
I have encountered a similar issue as you. I have uninstalled it from the extension, but I can still see a quick flash of the ad being skipped.However, the loading speed of new YouTube videos has not been affected.

What's strange is that I found that this issue only occurs when using the Edge browser and being logged into a YouTube account. 
If I use Edge's incognito mode or log into my YouTube account using Chrome, the ads display correctly.

I'm sorry if there is anything in the previous text that you don't understand. I'm not a native English speaker, so I'm using translation.

**Comment by 0x48piraj** [comment]
It's the problem with YouTube injecting a ton of useless DOM elements which FadBlock has to go through. The lag stabilises after a while and YouTube starts working smoothly.

I am working on targeting the skip button more accurately to increase the performance. Still, it will be delayed a bit as there are higher-priority issues coming in the next update.
