### ISSUE TITLE
Still working after removed

### ISSUE THREAD

**Issue by Eustella0510** [0x48piraj/fadblock#75]
My system is Win11, and both Edge and Chrome have been updated to the latest versions. The day before yesterday, I removed this extension from both browsers. However, when I use Edge, it quickly loads ads and then skips them, just like the extension is still working.

This only happens when I use Edge with my YouTube account logged in. When I'm in Edge's incognito mode or using Chrome with my account logged in (not incognito mode), the ads display normally, which is not skipped.

I want to know if anyone else has a similar situation and how I can resolve it.

**Comment by harkai84** [comment]
Try reinstall your browser(s).

**Comment by 0x48piraj** [comment]
That's not possible, it probably means you uninstalled and kept using the same tab that had the script loaded in runtime.

It's an extension not Ghost in the Shell, don't scare me like that!

**Comment by Eustella0510** [comment]
After I reinstalled the browser, everything's smooth sailing now. My bad for the scare!
