### ISSUE TITLE
About extensionpay.com

### ISSUE THREAD

**Issue by Nghia323223** [0x48piraj/fadblock#77]
Job well done, how can I pay and get a lifetime license for you?

**Comment by harkai84** [comment]
You can also book directly in the Fadblock Pro extension.
If you have already paid, simply enter your email address and click on the link that was sent to you.

**Comment by Nghia323223** [comment]
Where is the extension? I can't manage to find it in the web store.

**Comment by harkai84** [comment]
https://chrome.google.com/webstore/detail/fadblock-friendly-adblock/mdadjjfmjhfcibgfhfjbaiiljpllkbfc

**Comment by Nghia323223** [comment]
The field for the purchase of license is not present, do I have to wait for it to show up and pay only by then? You deserve a license key for what you do, that's why the payment site should be there

**Comment by 0x48piraj** [comment]
Thank you for helping out @harkai84. @Nghia323223, I am having some problems with ExtensionPay as cross-border card payments are often flagged as suspicious.

You can Paypal me over: https://www.paypal.me/piyushella

After you do, I can add your email and send you the instructions on how to activate the membership.

**Comment by Nghia323223** [comment]
How much to pay, I only have a visa card and i'm underage.

**Comment by Nghia323223** [comment]
Is there any other way to get the key? And how to enter it?

**Comment by Nghia323223** [comment]
I only have a visa card.

**Comment by 0x48piraj** [comment]
It's 5.99$ for lifetime, you can pay via card using the extension payment system after you get the popup.

**Comment by Nghia323223** [comment]
Is there an device limit?

**Comment by 0x48piraj** [comment]
Nope. You can use it on any number of devices. Just log in as you did with your primary devices.
