### ISSUE TITLE
Trying to pay the supposed "Lifetime license" simply crashes the browser and the payment doesn't go through(Opera GX)

### ISSUE THREAD

**Issue by KnightGabriel** [0x48piraj/fadblock#78]
For a while this extension worked pretty well outside the occasional minor hiccup. But now I'm constantly getting these stupid pop-ups to pay $6. Since it claims it's a one-time payment, I thought "oh, well that's nothing". But I've tried to pay twice already now, and both times it just crashed the browser without anything actually going through.

I'm extremely disappointed. I thought this developer was trustworthy and his extension was actually working, but now he's completely thrown that trust out of the window with this single update. A pop-up that frequently appears every couple videos and obstructs the screen while preventing you from clicking anything in the video is just as, if not worse than the ads.

**Comment by KnightGabriel** [comment]
@0x48piraj Can you please respond I keep getting this stupid pop-up despite me literally having tried to pay twice

**Comment by 0x48piraj** [comment]
I didn't receive any payments as far as I can see on my dashboard, you can check your bank statements and probably will see failed transactions, if the transactions got processed, you will get it in 3-4 days and if not, I will refund you the other payment, so don't worry. Cross-border payments are getting flagged as suspicious for obvious reasons. I have added PayPal as well, that should smoothen the process.

Can you email me over 0x48piraj@gmail.com so I can manually add you regardless of the payments and we can clear it up later?
