### ISSUE TITLE
Pro pop up

### ISSUE THREAD

**Issue by rexzooly** [0x48piraj/fadblock#79]
I know you have worked hard on this but this fucking pop up as shown it's self so many times it's worse then the fucking youtube videos you are meant to be helping with, there are many people that can't pay for this and you keep showing this is just sick and wrong I been on the PC for like a hour a seen your pop up at lest 15 times have a option to disable it or something.

I get you need to say hey I need help we all get this but this is out of line now, fix it please sorry but this as really made my time youtube worse then been there without any ad blockers.

If you are now changing the tool make it clear and then disabled the tool so we don't get any problems anymore but this as wasted more time then it's worth.

**Comment by 0x48piraj** [comment]
I understand your issues and the overall experience is similar among the masses, I messed up a lot, the initial popup comes after ~500 ads which I thought was a good enough time where it'll be okay to show the popup with high frequency, not a good decision.

I have already significantly reduced the frequency of the popup and it'll take the dev team a day or two to give it the green light and roll out the new version.

I know everyone can't pay and that's okay, I have added a lot of people who have reached out to me saying so. I am more than happy to give licenses to those who ask nicely, and as said, have adjusted the popup frequency and waiting for the new update to be published.

**Comment by rexzooly** [comment]
Thank you for the reply and sorry for the bad language I wasn't very well myself that day and everything was stressing me out I could of worded things much better but at the same time I really do like the fact you replied to me, if you can update this post when the update is out so I can test it with our setup and see if the new changes is much better.
