### ISSUE TITLE
(suggestion) mute ads

### ISSUE THREAD

**Issue by 7ih** [0x48piraj/fadblock#8]
Thank you for this amazing extension, it made me realize how much I take adblock for granted. Really small nitpick is I'll be playing some music and between songs i'll sometimes hear a tenth of a second of an ad before it skips it. Would appreciate if ads could be muted to remove the small disturbance.

**Comment by owaisali10** [comment]
Need to add videoPlayer.volume = 0; in content.js files. Provide write access and I could do it.

**Comment by 0x48piraj** [comment]
Adressed in https://github.com/0x48piraj/fadblock/commit/8b263b13ee346295a4b26577ae1f10e6f37f71d0. Closing.
