### ISSUE TITLE
fadblock pro

### ISSUE THREAD

**Issue by RWitteBusje023** [0x48piraj/fadblock#82]
hi, this new fadblock pro popup has been happening more often then actual youtube ads, is there any way to fix this? this extension is amazing and i would like to be able to use it further. i also just cant pay for this. can i turn these off somehow?

**Comment by 0x48piraj** [comment]
I am sorry for the inconvenience caused. I didn't know people in the States are getting upwards of 4 ads per video, that is making the popups incessant.

The initial popup comes after ~500 ads which I thought was a good enough time where it'll be okay to show the popup with high frequency (after every 3rd ad is blocked), not a good decision.

I have already significantly reduced the frequency of the popup and it'll take the dev team a day or two to give it the green light and roll out the new version.

Hope you can hold out till then, or disable it until the new version drops.

If you can't pay for it and still want the license, please email me at 0x48piraj@gmail.com and I will be happy to give unlimited license to you.

Again, I am sorry for the bad user experience.

**Comment by RWitteBusje023** [comment]
hello, thank you for the license, and for the support, i understand you made a mistake, things happen and you are doing something amazing by making this availible for everyone, keep up the good work and have a nice rest of your day.

**Comment by 0x48piraj** [comment]
Closing.
