### ISSUE TITLE
Does not block anything at al anymore.

### ISSUE THREAD

**Issue by Michelmilads** [0x48piraj/fadblock#83]
So al day today (8/11) fadblock hasnot blocked a single video for me, it has been stuck on 99 since yesterday and wont go above it, i dont even get the pop up message about buying a lifetime ticket or anything either. idk what has happend

**Comment by Michelmilads** [comment]
So i am using the latest version, since yesterday i have not gotten a single popup from fadblock asking me to buy a license or anything at all. Its just regular commercials on every video ive watched on today, Been looking on fadblock extension to se if the number gets higher but it has been stuck on 99 since this morning. I have refreshed the tab, i have closed down chrome all together and i have restarted my pc, nothing helps for some weird reason

**Comment by 0x48piraj** [comment]
That's completely weird. Not gonna lie.

How about uninstalling and reinstalling the extension, this is a completely unknown bug, do the uninstall-refresh-thebrowser-install-again switcharoo and if it doesn't help. I will have to take a deeper look (I tried the dev version to quickly set it to 99 ads and run through an ad and it works for me, screenshot below).

![image](https://github.com/0x48piraj/fadblock/assets/5800726/f02f4939-6ad6-4d65-81fa-1cea8b7826cc)

**Comment by Michelmilads** [comment]
Been trying to do that now for 2 hours or so, wont work, like it has worked FLAWLES until today, now it is stuck on 0 ads blocked. So after ive uninstalled it, restarted the browser and installed it again, the count went from 99 to 0 but yet it wont block anything, it has stayed on 9 ever since.

**Comment by 0x48piraj** [comment]
This is concerning,  can you go to `chrome://extensions` and see if FadBlock has registered any errors, and if it has, can you click on the `Errors` button and post the screenshot?

**Comment by Michelmilads** [comment]
here u go, the same issue remains today, i dont know what to do
![fadblock1](https://github.com/0x48piraj/fadblock/assets/143592366/1100fecf-031c-48fc-81f2-9f771dab4c09)
![fadblock2](https://github.com/0x48piraj/fadblock/assets/143592366/398ec058-7518-4af5-a6cc-e97a7d40e6cb)

**Comment by 0x48piraj** [comment]
This issue slipped up, does 2.6 works for you now?
