### ISSUE TITLE
not skipping ads

### ISSUE THREAD

**Issue by RWitteBusje023** [0x48piraj/fadblock#84]
Hi, its not skipping ads for me anymore, already reinstalled but stuck at 74 ads skipped.

**Comment by 0x48piraj** [comment]
Thank you for providing the details @RWitteBusje023. can you dump the current DOM state so I can examine it closely? (it's working for me as well as the majority as of now)

**How to?**
> When FadBlock doesn't work on a specific ad, while the ad is showing, pause the ad, then using the Web Inspector (F12), go to the Elements tab, right-click on the `<html>` tag in your code, and select `Copy`->`Copy outerHTML`. Then paste that into a new file and save.

**Comment by RWitteBusje023** [comment]
Hi, its not a specific ad that's not being skipped, none of the ads are getting skipped.

**Comment by 0x48piraj** [comment]
Just pick an ad, and do the following so I can analyze the issue because it's working fine for me. YouTube likes to test new patches with certain users and locations so without reports I can't do much until it's globally applied.

**Comment by Farseer123456789** [comment]
I purchased the premium version of the extension and it's stopped blocking ads at 107 ads blocked

**Comment by 0x48piraj** [comment]
Thank you for providing the details @Farseer123456789. can you dump the current DOM state so I can examine it closely? (it's working for me as well as the majority as of now)

**How to?**
> When FadBlock doesn't work on a specific ad, while the ad is showing, pause the ad, then using the Web Inspector (F12), go to the Elements tab, right-click on the `<html>` tag in your code, and select `Copy`->`Copy outerHTML`. Then paste that into a new file and save.

**Comment by BouquetofDiamonds** [comment]
No longer skipping ads on videos for me, either. It was working perfectly fine until today. However, every time I try to dump the dom to help, my tab freezes. Maybe it's just my Chromebook.

**Comment by Farseer123456789** [comment]
> Thank you for providing the details @Farseer123456789. can you dump the current DOM state so I can examine it closely? (it's working for me as well as the majority as of now)
> 
> **How to?**
> 
> > When FadBlock doesn't work on a specific ad, while the ad is showing, pause the ad, then using the Web Inspector (F12), go to the Elements tab, right-click on the `<html>` tag in your code, and select `Copy`->`Copy outerHTML`. Then paste that into a new file and save.
> 
> **Edit:** It's late in my timezone and I have been working all day on the project. I will look into the issue with a fresh set of eyes. Anyone who finds this issue, please dump the DOM so I can investigate and quickly release a patch.

I'm sorry but I have no idea how to do that

**Comment by 0x48piraj** [comment]
@BouquetofDiamonds seems like it's a similar case to https://github.com/0x48piraj/fadblock/issues/85. I am fried for today, I will look into the issue tomorrow, hopefully till then the new version will drop freeing me to work on these new issues.

**Comment by BouquetofDiamonds** [comment]
Thank you so much! I hope you know that your hard work is appreciated and loved! Enjoy your rest!
    On Wednesday, November 8, 2023 at 04:03:40 PM EST, Piyush Raj ***@***.***> wrote:  
 
 


@BouquetofDiamonds seems like it's a similar case to #85. I am fried for today, I will look into the issue tomorrow, hopefully till then the new version will drop freeing me to work on these new issues.

**Comment by TheNamor** [comment]
In case not I have an example ad that was not caught.
[example_ad.txt](https://github.com/0x48piraj/fadblock/files/13301292/example_ad.txt)

**Comment by YoukaiTheGit** [comment]
Another example of an ad in the middle of a video: 
[ad.txt](https://github.com/0x48piraj/fadblock/files/13302398/ad.txt)

**Comment by YoukaiTheGit** [comment]
Capture of the DOM  before (while main video is playing), during, and after an ad:
[video-before.txt](https://github.com/0x48piraj/fadblock/files/13302495/video-before.txt)
[ad1.txt](https://github.com/0x48piraj/fadblock/files/13302496/ad1.txt)
[video-after.txt](https://github.com/0x48piraj/fadblock/files/13302497/video-after.txt)

**Comment by 0x48piraj** [comment]
Doesn't seem like any DOM elements changes (`ad.txt`). Yes, the `ad-showing` and `ad-interrupting` classes are known to enter at the time of an ad.

If you're using Firefox, there can be a lot of compatibility issues as Firefox has inbuilt protection module called "Enhanced protection".

If you use Chrome, and can reproduce the bug, can you go to `chrome://extensions` and see if FadBlock has registered any errors, and if it has, can you click on the `Errors` button and post the screenshot?

**Comment by kwongtn** [comment]
Facing same issue, here are the files
[ad2.txt](https://github.com/0x48piraj/fadblock/files/13305772/ad2.txt)
[ad1.txt](https://github.com/0x48piraj/fadblock/files/13305773/ad1.txt)
[post_ad.txt](https://github.com/0x48piraj/fadblock/files/13305774/post_ad.txt)

Can't find logs though, am using 
- Microsoft Edge for Business Version 118.0.2088.69 (Official build) (64-bit)
- Fadblock 2.1

**Comment by 0x48piraj** [comment]
I have seen some reports where YouTube is banning individuals who were caught using uBlock or any traditional adblockers. Can you switch an account and test again?

**Comment by YoukaiTheGit** [comment]
I switched to Chrome, signed into Youtube with the same account, but could not reproduce the problem.  fadblock worked as expected there.  However, the extension version is 2.1.  In Firefox (which wasn't skipping ads), it is 2.2

**Comment by Letiz0** [comment]
[pausingAd.txt](https://github.com/0x48piraj/fadblock/files/13314619/pausingAd.txt)

I found they remove the node with .ytp-ad-preview-text class, is that the reason why it doesnt work anymore?
[src](https://github.com/0x48piraj/fadblock/blob/3ef3ec7ac972a39dbc2b7639aad75829be6fb633/src/chrome/js/background.js#L31)

![null1](https://github.com/0x48piraj/fadblock/assets/103472129/8b94dc2e-99d0-4931-92e3-78860703d723)
![null2](https://github.com/0x48piraj/fadblock/assets/103472129/727affcb-a4bd-46cb-930f-71dc5c5dbec3)

**Comment by RWitteBusje023** [comment]
Hello, sorry for late response, here is a copy of the html.
[ad.txt](https://github.com/0x48piraj/fadblock/files/13320852/ad.txt)

**Comment by 0x48piraj** [comment]
**The new version (2.5) is out on Chrome! LFG!**
