### ISSUE TITLE
YouTube is constantly testing and making the website slow [not a FadBlock issue] [not tested thoroughly]

### ISSUE THREAD

**Issue by ItsTepsu** [0x48piraj/fadblock#85]
Sometimes when using fadblock, the ad itself will be skipped to the end, but I have to manually click the "skip ad" button. 

This usually happens when YouTube is either **not loading or is loading slowly** (I believe this is from the new features YouTube has implemented, I've noticed the site has slowed down significantly since October)

**Comment by 0x48piraj** [comment]
If you have reached the limit, you have to "cancel" and reload the tab.

And seems like YouTube is injecting a lot of useless DOM elements to slow the search, I am working on some optimizations but it will need heavy testing as it can be a breaking change and the userbase is very volatile right now so I have delayed the patch for two updates. As reported in other threads, once YouTube is loaded, the lag should go away significantly, is that the case with you as well?

**Comment by ItsTepsu** [comment]
The website remains slow, and the ad blocking functionality still works by skimming the ads. The problem is, sometimes the ad doesn't actually get skipped and is just left with a blank screen and the skip ad button. I'm currently trying to replicate it for a screenshot to show you what I mean.

It's 100% YouTube thing as I uninstalled fadblock and tested the site again, which did not have an effect on the speed of the website. (For reference, my current Up-Down speeds are sitting ~40mbps) 

Also here's a list of my currently enabled extensions for YouTube

- VidIq
- Return YouTube Dislike
- BetterTTV (Works on YouTube livestream chats)

**Comment by 0x48piraj** [comment]
As I said, YouTube is testing a lot of things and doing a hell lot of nonsense.

Still, FadBlock can use some performance issues and they will be applied after the frequency issue has been stabilized.

**Comment by ItsTepsu** [comment]
For now I think the best bet is to assume that it is just YouTube being slow from all the random nonsense they've been adding, which is causing the ads to not be skipped. I'll add on here if I can figure out exactly what is causing it, but I have no background in this kind of stuff yet so it'll be unlikely I find anything if use.

**Comment by 0x48piraj** [comment]
I will be keeping an eye as well and won't be closing the issue, but will be changing the title according to your test results (to avoid causing unnecessary panic among users).

**Comment by GitDepository** [comment]
The title "Sometimes Fails to Skip Ads" will cause panic? Lmfao

**Comment by ItsTepsu** [comment]
**Update**

As of 14/11/23, YouTube seems to have been updated and is now running better. Still slower than before, but significantly better.

**Comment by 0x48piraj** [comment]
@GitDepository, oh I wish I could tell you all about the drama but oh well, seems like the new version is quite stable. Closing.
