### ISSUE TITLE
Fadblock now generates ads of it's own!

### ISSUE THREAD

**Issue by gnawsome** [0x48piraj/fadblock#86]
Your pop up freezes my browser now until I click on it to dismiss it.  how is that any different than what youtube was doing with the popup?

**Comment by Otmanraad** [comment]
It keep showing popups everytime I refresh the page, so it worse then ads lol, 

I uninstalled it cuz it was more annoying then watching 2 ads every now and then.

**Comment by Otmanraad** [comment]
To be clear I do like supporting the creator of such projects but I sadly I do not or can not contribute

Forcing me to close the popups every single time even if I can't even support is like watching youtube ads I won't buy/click on it so its a waste of time.

**Comment by gotexis** [comment]
with tampermonkey, include a script like such:

```js
setInterval(function() {
    var closeButton = document.getElementById('close-modal');
    if (closeButton) {
        closeButton.click();
    }
}, 50); // runs every 50 milliseconds
```

this will close the modal automatically.

**Comment by 0x48piraj** [comment]
@Otmanraad, I am sorry for the inconvenience caused. I didn't knew people in the States are getting upwards of 4 ads per video, that is making the popups incessant.

The initial popup comes after ~500 ads which I thought was a good enough time where it'll be okay to show the popup with high frequency (after every 3rd ad blocked), not a good decision.

I have already significantly reduced the frequency of the popup and it'll take the dev team a day or two to give it the green light and roll out the new version.

Hope you can hold out till then, or disable it until the new version drops.

**Comment by gnawsome** [comment]
Thanks actually super reasonable thank you!
