### ISSUE TITLE
Ads no longer being skipped

### ISSUE THREAD

**Issue by tonycarnell** [0x48piraj/fadblock#89]
Hi,

Like other users have noted, FadBlock is no longer skipping ads for me.

I don't know if there's a connection but I purchased a license two days ago.

I'm using Chrome on a Mac (I've also tried FadBlock on a completely clean install of Firefox but with the same result).

I've followed the instructions to 'dump the current dom' I've seen on other posts, and have attached it. I hope I've done it correctly.

I've also attached a grab showing the extensions I have installed in Chrome. All those that may have any effect on YouTube have been disabled (I've disabled uBlock for YouTube and I've also tried fully disabling it but without any difference).

I hope this can get resolved soon.

[dom.docx](https://github.com/0x48piraj/fadblock/files/13313260/dom.docx)
![extensions](https://github.com/0x48piraj/fadblock/assets/13287217/3555707f-b6cd-4a5e-9aa3-ab186f015669)

**Comment by rawcomposition** [comment]
I'm noticing the same thing. It was working last night, but not tonight.

**Comment by JaielZeus** [comment]
Same here @0x48piraj

**Comment by basant1994** [comment]
You can use this in the meanwhile for chrome: https://chrome.google.com/webstore/detail/youtube-adblock-by-friend/ehfcoplbhoohillcmlophcfghpeilfjc

**Comment by 0x48piraj** [comment]
Lots of people have reported the extension in the past for data theft (me included), didn't work at the start when I decided to make the extension as well, if it works, great, open a Reddit thread or something. DO NOT POST ANY ROUGUE EXTENSIONS HERE.

As for @JaielZeus and @rawcomposition do you have uBlock Origin installed and enabled as the OP has?

Because if that's the case, your account has probably been detected using uBlock and has been banned. Here's the report: https://github.com/0x48piraj/fadblock/issues/87

**Comment by JaielZeus** [comment]
@0x48piraj I have not. The only extensions I have is Adblocker, which is paused on YT and your extension plus 2 unimportant/unrelated ones. I thought youtube has counteracted the fast forwarding of ads that your blocker employs maybe. I jsut paid for premium the other day and that's kinda a bummer that it doesn't work anymore now.

![image](https://github.com/0x48piraj/fadblock/assets/42944799/feddbedc-a628-4ea8-bfdd-91b4b27c6a33)

**Comment by 0x48piraj** [comment]
Kindly refrain from using alternative ad blockers, especially if you've supported FadBlock through a donation. Some users combining multiple ad blockers, against the FAQ's advice, are facing detection issues, resulting in YouTube account bans. Iit's not a FadBlock issue in any way. It is working for people who are only using FadBlock.

**Note:** If YouTube has banned you, removing Adblocker Plus/Ultimate, uBlock won't work as YouTube has logged your IP, device and account data into their ban list.

Here's a Reddit thread which proves the above remark: https://www.reddit.com/r/Adblock/comments/17rluvd/purging_caches_refreshing_in_ublock_on_firefox/

**Comment by JaielZeus** [comment]
@0x48piraj It is installed yes but it is paused on Youtube and fadblocker has suddenly stopped working. I have removed the adblocker completely now to see if I get fadblock to work again but I doubt it somehow, we will see in a few minutes when youtube sends some ads my way again

**Comment by JaielZeus** [comment]
Let me tell you my setup as of now:

![image](https://github.com/0x48piraj/fadblock/assets/42944799/a08f694d-e8e4-42da-88cf-8fcc9e1e68d7)
![image](https://github.com/0x48piraj/fadblock/assets/42944799/30b753ce-512d-4806-89fd-b4dc497a5a51)

Windows 11 Education version if that matters.

Woke up today and got not ad skipping anymore, it just does not work and I am getting the aforementioned errors in the console, which tell us the element that the script is trying to fetch from the dom is just not loaded and hence the whole script cannot work for skipping. It seems your scrupt is laoded and executed before the dom can load to me, if it helps. The error is the whole reason why your script doesn't do it's thing.

![image](https://github.com/0x48piraj/fadblock/assets/42944799/36bd533d-da95-4ce0-879d-0e2413c702c4)

![image](https://github.com/0x48piraj/fadblock/assets/42944799/11855bb7-26c1-41c7-86f4-441daf45eac6)

**Comment by 0x48piraj** [comment]
**The new version (2.5) is out on Chrome! LFG!**
