### ISSUE TITLE
Premium fadblock paid.

### ISSUE THREAD

**Issue by Meza85** [0x48piraj/fadblock#90]
ads plays as if i had no adblocker and i also paid for premium and i have my receipt so yeah riperino. im not watching ads so rip youtube until its working again.

**Comment by 0x48piraj** [comment]
Kindly refrain from using alternative ad blockers, especially if you've supported FadBlock through a donation. Some users combining multiple ad blockers, against the FAQ's advice, are facing detection issues, resulting in YouTube account bans. It's not a FadBlock issue in any way. It is working for people who are only using FadBlock.

**Note:** If YouTube has banned you, removing Adblocker Plus/Ultimate, uBlock won't work as YouTube has logged your IP, device and account data into their ban list.

Here's a Reddit thread that proves the above remark: https://www.reddit.com/r/Adblock/comments/17rluvd/purging_caches_refreshing_in_ublock_on_firefox/

I will be looking closely into it anyways.

**Comment by Meza85** [comment]
Ok but if im not using another ad how does the ads stop being fast
forwarding? what could be the cause if i know for a fact that im not using
any alternate adblocker ? Thanks.

Le ven. 10 nov. 2023 à 07:55, Piyush Raj ***@***.***> a
écrit :

**Comment by Meza85** [comment]
[image: image.png]

**Comment by Meza85** [comment]
[image: image.png]
[image: image.png]
