### ISSUE TITLE
FadBlock doesn't work in 119 Chrome

### ISSUE THREAD

**Issue by huanhoahongso3-collab** [0x48piraj/fadblock#91]
Hi there, I installed FadBlock for a week. It still worked normal until yesterday, when I updated my Chrome Version to 119. It still show ads  as normal

Note: 118 Chrome still works

**Comment by huanhoahongso3-collab** [comment]
![Screenshot 2023-11-10 140807](https://github.com/0x48piraj/fadblock/assets/144003289/cd3a7889-11ce-4a34-a8bc-0377e4c5fbaf)
Chrome on Windows 11

**Comment by RandyLatteph** [comment]
Same. It still worked untill last night but not working today.
Stopped at"Video Ads blocked since installation 110".

**Comment by harkai84** [comment]
I have chrome 120.0.6099.18 Beta and it still works.

**Comment by Kelsinga** [comment]
Not sure if it's chrome.
I'm on vivaldi and it worked yesterday and not today.
chromium based, but not sure if I had an update

**Comment by 0x48piraj** [comment]
Kindly refrain from using alternative ad blockers, especially if you've supported FadBlock through a donation. Some users combining multiple ad blockers, against the FAQ's advice, are facing detection issues, resulting in YouTube account bans. It's not a FadBlock issue in any way. It is working for people who are only using FadBlock.

**Note:** If YouTube has banned you, removing Adblocker Plus/Ultimate, uBlock won't work as YouTube has logged your IP, device and account data into their ban list.

Here's a Reddit thread that proves the above remark: https://www.reddit.com/r/Adblock/comments/17rluvd/purging_caches_refreshing_in_ublock_on_firefox/

**Comment by RandyLatteph** [comment]
But I only use Fadblock

**Comment by 0x48piraj** [comment]
@RandyLatteph, I am again looking into the YouTube source and investigating as more reports are coming in.

**Comment by huanhoahongso3-collab** [comment]
After I removed cookies of youtube.com, everything is fine now

**Comment by YoukaiTheGit** [comment]
fadblock in Chrome had been working for me before today, but today it was not.  
chrome 119, fadblock 25:
[During ad: chrome25ad1.txt](https://github.com/0x48piraj/fadblock/files/13353558/chrome25ad1.txt)
[After ad: chrome25ad1-after.txt](https://github.com/0x48piraj/fadblock/files/13353560/chrome25ad1-after.txt)

fadblock was just updated to version 25 today.  I do not know what version of Chrome I was running before today.

**Comment by huanhoahongso3-collab** [comment]
But after 2 days after reset cookies, it still doesn't skip ads

**Comment by 0x48piraj** [comment]
2.6 working consistently, closing.
