### ISSUE TITLE
Fadblock no longer working in Firefox

### ISSUE THREAD

**Issue by hockeynl** [0x48piraj/fadblock#92]
Starting tonight Fadblock no longer blocks any ads in Firefox.

**Comment by harkai84** [comment]
What browser and extensions do you use?

**Comment by 0x48piraj** [comment]
Kindly refrain from using alternative ad blockers, especially if you've supported FadBlock through a donation. Some users combining multiple ad blockers, against the FAQ's advice, are facing detection issues, resulting in YouTube account bans. It's not a FadBlock issue in any way. It is working for people who are only using FadBlock.

**Note:** If YouTube has banned you, removing Adblocker Plus/Ultimate, uBlock won't work as YouTube has logged your IP, device and account data into their ban list.

Here's a Reddit thread that proves the above remark: https://www.reddit.com/r/Adblock/comments/17rluvd/purging_caches_refreshing_in_ublock_on_firefox/

**Comment by hockeynl** [comment]
> Kindly refrain from using alternative ad blockers, especially if you've supported FadBlock through a donation. Some users combining multiple ad blockers, against the FAQ's advice, are facing detection issues, resulting in YouTube account bans. It's not a FadBlock issue in any way. It is working for people who are only using FadBlock.
> 
> **Note:** If YouTube has banned you, removing Adblocker Plus/Ultimate, uBlock won't work as YouTube has logged your IP, device and account data into their ban list.
> 
> Here's a Reddit thread that proves the above remark: https://www.reddit.com/r/Adblock/comments/17rluvd/purging_caches_refreshing_in_ublock_on_firefox/

Sorry for the the ate reply. Te issue was that Fadblock was still on 1.3 and when it updated to 2.1 later it was working.

**Comment by 0x48piraj** [comment]
2.6 working consistently, closing.
