### ISSUE TITLE
no ads since yesterday :(

### ISSUE THREAD

**Issue by ozzyozyrys** [0x48piraj/fadblock#93]
no ads since yesterday :(

**Comment by harkai84** [comment]
I don't understand you. If there is no advertising then why are you sad. It's a good thing.

**Comment by ozzyozyrys** [comment]
ads are not blocked,and that's the problem :(

pt., 10 lis 2023 o 10:47 harkai84 ***@***.***> napisał(a):

**Comment by harkai84** [comment]
We need more information.
Which browser and extensions do you use?
What types of advertising are not blocked?

**Comment by Shirkit** [comment]
Hello,

The video ads (before play and while playing) are both displaying, both skippable and non-skippable ads are playing. I'm using Firefox 119.0.1 with FAD 2.2 on Windows 11.

**Comment by harkai84** [comment]
Hi Shirkit,
you should make a new issue thread.

**Comment by 0x48piraj** [comment]
Kindly refrain from using alternative ad blockers, especially if you've supported FadBlock through a donation. Some users combining multiple ad blockers, against the FAQ's advice, are facing detection issues, resulting in YouTube account bans. It's not a FadBlock issue in any way. It is working for people who are only using FadBlock.

**Note:** If YouTube has banned you, removing Adblocker Plus/Ultimate, uBlock won't work as YouTube has logged your IP, device and account data into their ban list.

Here's a Reddit thread that proves the above remark: https://www.reddit.com/r/Adblock/comments/17rluvd/purging_caches_refreshing_in_ublock_on_firefox/

**Comment by 0x48piraj** [comment]
THE NEW VERSION IS OUT! LFG!!!
