### ISSUE TITLE
Very confused about issue numbers....

### ISSUE THREAD

**Issue by amiles5** [0x48piraj/fadblock#94]
Github says 1.3 but I have 2.1 

confused
![Screenshot 2023-11-10 at 10 51 09](https://github.com/0x48piraj/fadblock/assets/12343787/b04fb463-f48e-4635-b226-07c2496db723)

**Comment by 0x48piraj** [comment]
Read the announcement to know more.

**Comment by amiles5** [comment]
The announcement does not help - where is code for 2.1 ?
