### ISSUE TITLE
On unescapable ad the extension does'nt work everytime,but I have a solution.

### ISSUE THREAD

**Issue by zolexander** [0x48piraj/fadblock#98]
In the background.js the skipLock or Surveylock variable on unescapable ads becomes undefined. Which is: I can't tell That cause the hole problem. Every time when an ad non-escapable the extension can't escape others anymore. To escape such ad: that condition does'nt necessary to check. I will send  later a pull request related to this issue.

**Comment by 0x48piraj** [comment]
The new version is out on Chrome!

Please update!
