### ISSUE TITLE
Doesn't block ads on Firefox since today.

### ISSUE THREAD

**Issue by kadxe** [0x48piraj/fadblock#99]
Since today ads are no longer blocked on Firefox. It worked great yesterday.
No other extensions but one that I disabled with the problem still being present.

**Comment by Peter-Ries** [comment]
+1 for me too, incgnito seems to work (Chrome Browser)

**Comment by Confused011** [comment]
+1 I'm getting ads on chrome as well

**Comment by Aritton** [comment]
Same. it doesnt work anymore and I dont have any other adblockers installed.

**Comment by TheLyricalSystem** [comment]
same here, no other ad blockers enabled.

**Comment by Mojubabox** [comment]
Same issue as others. No other Adblockers installed.

**Comment by 0x48piraj** [comment]
That's weird, you guys sure you didn't have any adblockers to begin with?

See here, https://github.com/0x48piraj/fadblock/issues/88, https://github.com/0x48piraj/fadblock/issues/89, https://github.com/0x48piraj/fadblock/issues/87 (so many cases where people said they don't have any adblockers but were using one)

Anyways, today more reports have come in, so I will try to reproduce this issue again and let you know if FadBlock has been patched in geo-specific zones or uBlock is still the culprit.

Let's move to a single thread (https://github.com/0x48piraj/fadblock/issues/103) so I can cumulate all the responses, closing this one.
